#!/usr/bin/env python
# Generates src/style/css_property_names.{h,cc} from Blink's
# css_properties.json5, using Blink's own loader and property ordering
# (build/scripts/core/css/css_properties.py). The output is checked in; rerun
# after updating the pinned Chromium sources or the ported property list:
#
#   python tools/style/make_css_properties.py <chromium-src> src/style
#
# Only the ported properties are emitted. They keep the relative order of the
# upstream CSSPropertyID enum: high-priority longhands first, then the other
# longhands, then the shorthands, then the aliases. Upstream numbering is not
# kept. Parser-only data (parse functions, CSSOM exposure, use counters) is
# omitted: there is no CSS parser.

import os
import sys

# Longhands and shorthands, by CSS name. Aliases of these are added
# automatically. Runtime-flagged properties are included only when the flag is
# 'stable' upstream (see main()).
PORTED_PROPERTIES = [
    # Fonts.
    'font-family',
    'font-feature-settings',
    'font-kerning',
    'font-optical-sizing',
    'font-palette',
    'font-size',
    'font-size-adjust',
    'font-stretch',
    'font-style',
    'font-synthesis-small-caps',
    'font-synthesis-style',
    'font-synthesis-weight',
    'font-variant-alternates',
    'font-variant-caps',
    'font-variant-east-asian',
    'font-variant-emoji',
    'font-variant-ligatures',
    'font-variant-numeric',
    'font-variant-position',
    'font-variation-settings',
    'font-weight',
    'text-rendering',
    '-webkit-font-smoothing',
    '-webkit-locale',
    'font',
    'font-synthesis',
    'font-variant',
    # Direction, writing mode and line breaking.
    'direction',
    'unicode-bidi',
    'writing-mode',
    '-webkit-writing-mode',
    'text-orientation',
    '-webkit-text-orientation',
    'word-break',
    '-webkit-line-break',
    'line-break',
    'overflow-wrap',
    # Text layout.
    'color',
    'hyphenate-character',
    'hyphenate-limit-chars',
    'hyphens',
    'letter-spacing',
    'line-height',
    'tab-size',
    'text-align',
    'text-align-last',
    'text-autospace',
    'text-combine-upright',
    'text-indent',
    'text-spacing-trim',
    'text-transform',
    'text-wrap-mode',
    'text-wrap-style',
    'vertical-align',
    'visibility',
    'white-space-collapse',
    'word-spacing',
    'text-wrap',
    'white-space',
    # Decorations and text paint.
    'text-decoration-color',
    'text-decoration-line',
    'text-decoration-skip-ink',
    'text-decoration-style',
    'text-decoration-thickness',
    'text-emphasis-color',
    'text-emphasis-position',
    'text-emphasis-style',
    'text-shadow',
    'text-underline-offset',
    'text-underline-position',
    '-webkit-text-fill-color',
    '-webkit-text-stroke-color',
    '-webkit-text-stroke-width',
    'text-decoration',
    'text-emphasis',
    '-webkit-text-stroke',
]

HEADER_COMMENT = [
    '// Generated by tools/style/make_css_properties.py from',
    '// blink/renderer/core/css/css_properties.json5. Do not edit.',
    '// Copyright 2014 The Chromium Authors',
    '// Use of this source code is governed by a BSD-style license in LICENSE.',
]


def load(chromium_root):
    blink = os.path.join(chromium_root, 'third_party', 'blink', 'renderer')
    sys.path[:0] = [
        os.path.join(blink, 'build', 'scripts'),
        os.path.join(chromium_root, 'third_party', 'pyjson5', 'src'),
        os.path.join(chromium_root, 'third_party'),
    ]
    from core.css import css_properties
    import json5_generator

    paths = [
        os.path.join(blink, 'core', 'css', 'css_properties.json5'),
        os.path.join(blink, 'core', 'css',
                     'computed_style_field_aliases.json5'),
        os.path.join(blink, 'platform', 'runtime_enabled_features.json5'),
        os.path.join(blink, 'core', 'style',
                     'computed_style_extra_fields.json5'),
    ]
    css = css_properties.CSSProperties(paths)
    features = json5_generator.Json5File.load_from_files(
        [paths[2]]).name_dictionaries
    stable = {
        f['name'].original
        for f in features if f.get('status') == 'stable'
    }
    return css, stable


def target_name(alias):
    target = alias.alias_for
    if hasattr(target, 'name'):
        return target.name.original
    return str(target)


def select(css, stable):
    by_name = {p.name.original: p for p in css.longhands + css.shorthands}
    ported = set(PORTED_PROPERTIES)
    for name in PORTED_PROPERTIES:
        assert name in by_name, 'Unknown property %s' % name
    selected = []
    for p in css.longhands + css.shorthands:
        name = p.name.original
        if name not in ported:
            continue
        if p.runtime_flag and p.runtime_flag not in stable:
            continue
        selected.append(p)
    names = {p.name.original for p in selected}
    for p in selected:
        if p.surrogate_for:
            assert p.surrogate_for.name.original in names, p.name.original
        for longhand in p.longhands or []:
            assert longhand in names, '%s needs %s' % (p.name.original,
                                                       longhand)
    aliases = [a for a in css.aliases if target_name(a) in names]
    return selected, aliases


def enum_key(p):
    return p.enum_key


def generate_header(longhands, shorthands, aliases):
    lines = HEADER_COMMENT + [
        '#pragma once',
        '',
        '#include <cstdint>',
        '#include <span>',
        '#include <string_view>',
        '',
        'namespace bkit {',
        '',
        '// Only ported properties have IDs. Longhands come first (high-priority',
        '// longhands before the others), then shorthands, then aliases, each in',
        '// upstream order.',
        'enum class CSSPropertyID : uint16_t {',
        '  kInvalid = 0,',
    ]
    for p in longhands + shorthands:
        lines.append('  %s,' % enum_key(p))
    for a in aliases:
        lines.append('  %s,' % a.enum_key)
    lines += ['  kCount', '};', '']
    high = [p for p in longhands if p.priority > 0]
    lines += [
        'inline constexpr CSSPropertyID kFirstCSSProperty = CSSPropertyID::%s;'
        % enum_key(longhands[0]),
        'inline constexpr CSSPropertyID kLastHighPriorityCSSProperty = '
        'CSSPropertyID::%s;' % enum_key(high[-1]),
        'inline constexpr CSSPropertyID kLastLonghandCSSProperty = '
        'CSSPropertyID::%s;' % enum_key(longhands[-1]),
        'inline constexpr CSSPropertyID kFirstShorthandCSSProperty = '
        'CSSPropertyID::%s;' % enum_key(shorthands[0]),
        'inline constexpr CSSPropertyID kLastCSSProperty = CSSPropertyID::%s;'
        % enum_key(shorthands[-1]),
        'inline constexpr CSSPropertyID kFirstCSSPropertyAlias = '
        'CSSPropertyID::%s;' % aliases[0].enum_key,
        'inline constexpr int kNumCSSPropertyIDs = '
        'static_cast<int>(CSSPropertyID::kCount);',
        'inline constexpr int kNumCSSLonghands = %d;' % len(longhands),
        '',
        'constexpr bool IsHighPriority(CSSPropertyID id) {',
        '  return id >= kFirstCSSProperty && id <= kLastHighPriorityCSSProperty;',
        '}',
        'constexpr bool IsLonghand(CSSPropertyID id) {',
        '  return id >= kFirstCSSProperty && id <= kLastLonghandCSSProperty;',
        '}',
        'constexpr bool IsShorthand(CSSPropertyID id) {',
        '  return id >= kFirstShorthandCSSProperty && id <= kLastCSSProperty;',
        '}',
        'constexpr bool IsPropertyAlias(CSSPropertyID id) {',
        '  return id >= kFirstCSSPropertyAlias && id < CSSPropertyID::kCount;',
        '}',
        '',
        'struct CSSPropertyMetadata {',
        '  CSSPropertyID id;',
        '  std::string_view name;',
        '  bool inherited;',
        '  // css_properties.json5 "surrogate_for": a legacy longhand which is',
        '  // cascaded as the named property. kInvalid when none.',
        '  CSSPropertyID surrogate_for;',
        '  // css_properties.json5 "logical_property_group": the group name',
        '  // (empty when in none) and whether this member is the logical one.',
        '  std::string_view logical_property_group;',
        '  bool is_logical;',
        '  // The resolved property of an alias; kInvalid otherwise.',
        '  CSSPropertyID alias_for;',
        '  // The longhands a shorthand expands to, in StylePropertyShorthand',
        '  // order. Empty for longhands and aliases.',
        '  std::span<const CSSPropertyID> longhands;',
        '};',
        '',
        'std::span<const CSSPropertyMetadata> CSSProperties();',
        'const CSSPropertyMetadata* GetCSSPropertyMetadata(CSSPropertyID);',
        '// The property an alias stands for; other IDs are returned unchanged.',
        'CSSPropertyID ResolveCSSPropertyID(CSSPropertyID);',
        '// The ID of a property or alias by CSS name; kInvalid if not ported.',
        'CSSPropertyID CSSPropertyIDFromName(std::string_view);',
        '// CSSProperty::IsInSameLogicalPropertyGroupWithDifferentMappingLogic().',
        'bool IsInSameLogicalPropertyGroupWithDifferentMappingLogic(CSSPropertyID, CSSPropertyID);',
        '',
        '} // namespace bkit',
        '',
    ]
    return lines


def generate_source(longhands, shorthands, aliases):
    lines = HEADER_COMMENT + [
        '#include "css_property_names.h"',
        '',
        '#include <array>',
        '',
        'namespace bkit {',
        'namespace {',
        '',
    ]
    for p in shorthands:
        lines.append('constexpr CSSPropertyID k%sLonghands[] = {' %
                     p.name.to_upper_camel_case())
        for longhand in p.longhands:
            key = next(l for l in longhands if l.name.original == longhand)
            lines.append('    CSSPropertyID::%s,' % enum_key(key))
        lines.append('};')
    lines += ['', 'constexpr CSSPropertyMetadata kProperties[] = {']

    def entry(p, alias_for=None):
        name = p.name.original
        surrogate = ('CSSPropertyID::%s' % p.surrogate_for.enum_key
                     if getattr(p, 'surrogate_for', None) and not alias_for
                     else 'CSSPropertyID::kInvalid')
        group = getattr(p, 'logical_property_group', None) or {}
        group_name = group.get('name', '') if isinstance(group, dict) else ''
        if hasattr(group_name, 'original'):
            group_name = group_name.original
        is_logical = 'true' if getattr(p, 'is_logical', False) else 'false'
        target = ('CSSPropertyID::%s' % alias_for if alias_for else
                  'CSSPropertyID::kInvalid')
        longhand_list = ('k%sLonghands' % p.name.to_upper_camel_case()
                         if p.longhands and not alias_for else '{}')
        inherited = 'true' if p.inherited else 'false'
        return ('    {CSSPropertyID::%s, "%s", %s, %s, "%s", %s, %s, %s},' %
                (p.enum_key, name, inherited, surrogate, group_name,
                 is_logical, target, longhand_list))

    for p in longhands + shorthands:
        lines.append(entry(p))
    all_by_name = {p.name.original: p for p in longhands + shorthands}
    for a in aliases:
        lines.append(entry(a, enum_key(all_by_name[target_name(a)])))
    lines += [
        '};',
        'static_assert(std::size(kProperties) + 1 == static_cast<size_t>(CSSPropertyID::kCount));',
        '',
        'constexpr bool MetadataInIDOrder() {',
        '  for (size_t i = 0; i < std::size(kProperties); ++i)',
        '    if (static_cast<size_t>(kProperties[i].id) != i + 1) return false;',
        '  return true;',
        '}',
        'static_assert(MetadataInIDOrder());',
        '',
        '} // namespace',
        '',
        'std::span<const CSSPropertyMetadata> CSSProperties() {',
        '  return kProperties;',
        '}',
        '',
        'const CSSPropertyMetadata* GetCSSPropertyMetadata(CSSPropertyID id) {',
        '  const auto index = static_cast<size_t>(id);',
        '  return index > 0 && index < static_cast<size_t>(CSSPropertyID::kCount) ? &kProperties[index - 1] : nullptr;',
        '}',
        '',
        'CSSPropertyID ResolveCSSPropertyID(CSSPropertyID id) {',
        '  if (!IsPropertyAlias(id)) return id;',
        '  return GetCSSPropertyMetadata(id)->alias_for;',
        '}',
        '',
        'CSSPropertyID CSSPropertyIDFromName(std::string_view name) {',
        '  for (const auto& property : kProperties)',
        '    if (property.name == name) return property.id;',
        '  return CSSPropertyID::kInvalid;',
        '}',
        '',
        'bool IsInSameLogicalPropertyGroupWithDifferentMappingLogic(CSSPropertyID id, CSSPropertyID other) {',
        '  const auto* a = GetCSSPropertyMetadata(id);',
        '  const auto* b = GetCSSPropertyMetadata(other);',
        '  return a && b && !a->logical_property_group.empty() && a->logical_property_group == b->logical_property_group &&',
        '         a->is_logical != b->is_logical;',
        '}',
        '',
        '} // namespace bkit',
        '',
    ]
    return lines


def main(chromium_root, output_dir):
    css, stable = load(chromium_root)
    selected, aliases = select(css, stable)
    longhands = [p for p in selected if not p.longhands]
    shorthands = [p for p in selected if p.longhands]
    outputs = (
        ('css_property_names.h', generate_header(longhands, shorthands,
                                                 aliases)),
        ('css_property_names.cc', generate_source(longhands, shorthands,
                                                  aliases)),
    )
    for name, lines in outputs:
        with open(os.path.join(output_dir, name), 'w', encoding='utf-8',
                  newline='\n') as output:
            output.write('\n'.join(lines))


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit('usage: make_css_properties.py <chromium-src> <output-dir>')
    main(os.path.abspath(sys.argv[1]), os.path.abspath(sys.argv[2]))
