#!/usr/bin/env python
# Generates src/style/css_value_keywords.{h,cc} from Blink's
# core/css/css_value_keywords.json5, using Blink's own json5 loader and enum
# naming (build/scripts/core/css/make_css_value_keywords.py). The output is
# checked in; rerun after updating the pinned Chromium sources:
#
#   python tools/style/make_css_value_keywords.py <chromium-src> src/style
#
# Parser-only parts of the upstream output (the gperf FindValue() table and
# IsValueAllowedInMode()) are omitted: there is no CSS parser.

import os
import sys


def main(chromium_root, output_dir):
    scripts = os.path.join(chromium_root, 'third_party', 'blink', 'renderer',
                           'build', 'scripts')
    sys.path[:0] = [
        scripts,
        os.path.join(chromium_root, 'third_party', 'pyjson5', 'src')
    ]
    import json5_generator
    from name_utilities import enum_key_for_css_keyword

    json5_path = os.path.join(chromium_root, 'third_party', 'blink',
                              'renderer', 'core', 'css',
                              'css_value_keywords.json5')
    keywords = json5_generator.Json5File.load_from_files(
        [json5_path]).name_dictionaries
    first_keyword_id = 1
    names = [keyword['name'].original for keyword in keywords]
    enums = [enum_key_for_css_keyword(keyword['name']) for keyword in keywords]
    count = len(keywords) + first_keyword_id
    max_length = max(len(name) for name in names)

    header = [
        '// Generated by tools/style/make_css_value_keywords.py from',
        '// blink/renderer/core/css/css_value_keywords.json5. Do not edit.',
        '// Copyright 2014 The Chromium Authors',
        '// Use of this source code is governed by a BSD-style license in LICENSE.',
        '#pragma once',
        '',
        '#include <stddef.h>',
        '',
        '#include <string_view>',
        '',
        'namespace bkit {',
        '',
        'enum class CSSValueID {',
        '  kInvalid = 0,',
    ]
    header += [
        '  %s = %d,' % (enum, first_keyword_id + offset)
        for offset, enum in enumerate(enums)
    ]
    header += [
        '};',
        '',
        'constexpr int kNumCSSValueKeywords = %d;' % count,
        'constexpr size_t kMaxCSSValueKeywordLength = %d;' % max_length,
        '',
        'inline bool IsValidCSSValueID(CSSValueID id) {',
        '  return id != CSSValueID::kInvalid;',
        '}',
        '',
        'std::string_view GetCSSValueName(CSSValueID);',
        '',
        '} // namespace bkit',
        '',
    ]

    offsets = []
    current_offset = 0
    for name in names:
        offsets.append(current_offset)
        current_offset += len(name) + 1
    offsets.append(current_offset)

    source = [
        '// Generated by tools/style/make_css_value_keywords.py from',
        '// blink/renderer/core/css/css_value_keywords.json5. Do not edit.',
        '// Copyright 2014 The Chromium Authors',
        '// Use of this source code is governed by a BSD-style license in LICENSE.',
        '#include "css_value_keywords.h"',
        '',
        '#include <stdint.h>',
        '',
        'namespace bkit {',
        '',
        'static const char kValueListStringPool[] = {',
    ]
    source += ['  "%s\\0"' % name for name in names]
    source += [
        '};',
        '',
        'static const uint16_t kValueListStringOffsets[] = {',
    ]
    source += ['  %d,' % offset for offset in offsets]
    source += [
        '};',
        '',
        'std::string_view GetCSSValueName(CSSValueID id) {',
        '  const int raw_id = static_cast<int>(id);',
        '  const uint16_t start = kValueListStringOffsets[raw_id - 1];',
        '  // Subtract one to compensate for the null character.',
        '  const uint16_t end = kValueListStringOffsets[raw_id] - 1;',
        '  return std::string_view(kValueListStringPool + start, end - start);',
        '}',
        '',
        '} // namespace bkit',
        '',
    ]

    for name, lines in (('css_value_keywords.h', header),
                        ('css_value_keywords.cc', source)):
        with open(os.path.join(output_dir, name), 'w', encoding='utf-8',
                  newline='\n') as output:
            output.write('\n'.join(lines))


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit('usage: make_css_value_keywords.py <chromium-src> <output-dir>')
    main(os.path.abspath(sys.argv[1]), os.path.abspath(sys.argv[2]))
