// Generated by tools/style/make_computed_style_base.py from
// blink/renderer/core/css/css_properties.json5 and
// blink/renderer/core/style/computed_style_extra_fields.json5. Do not edit.
// Copyright 2016 The Chromium Authors
// Use of this source code is governed by a BSD-style license in LICENSE.
#include "computed_style_base.h"

namespace bkfont {

ComputedStyleBase::ComputedStyleBase()
    : inherited_data_(std::make_shared<StyleInheritedData>())
    , misc_inherited_data_(std::make_shared<StyleMiscInheritedData>())
    , box_data_(std::make_shared<StyleBoxData>())
    , visual_data_(std::make_shared<StyleVisualData>())
    , misc_data_(std::make_shared<StyleMiscData>())
    , data_{
        static_cast<unsigned>(ETextAlign::kStart) /* text_align_ */,
        static_cast<unsigned>(static_cast<unsigned>(EVerticalAlign::kBaseline)) /* vertical_align_ */,
        static_cast<unsigned>(ETextTransform::kNone) /* text_transform_ */,
        static_cast<unsigned>(UnicodeBidi::kNormal) /* unicode_bidi_ */,
        static_cast<unsigned>(WritingMode::kHorizontalTb) /* writing_mode_ */,
        static_cast<unsigned>(TextWrapStyle::kAuto) /* text_wrap_style_ */,
        static_cast<unsigned>(EVisibility::kVisible) /* visibility_ */,
        static_cast<unsigned>(WhiteSpaceCollapse::kCollapse) /* white_space_collapse_ */,
        static_cast<unsigned>(TextDirection::kLtr) /* direction_ */,
        static_cast<unsigned>(false) /* has_explicit_inheritance_ */,
        static_cast<unsigned>(TextWrapMode::kWrap) /* text_wrap_mode_ */
      }
{}

ComputedStyleBase::ComputedStyleBase(const ComputedStyleBuilderBase& builder)
    : inherited_data_(builder.inherited_data_)
    , misc_inherited_data_(builder.misc_inherited_data_)
    , box_data_(builder.box_data_)
    , visual_data_(builder.visual_data_)
    , misc_data_(builder.misc_data_)
    , data_(builder.data_)
{
  builder.ResetAccess();
}

ComputedStyleBase::StyleInheritedData::StyleInheritedData()
    : font_(Font())
    , legacy_paint_(PlatformPaint())
    , line_height_(Length::Auto())
    , legacy_baseline_shift_(LayoutUnit())
{}

ComputedStyleBase::StyleMiscInherited1Data::StyleMiscInherited1Data()
    : hyphenation_string_(AtomicString())
    , text_indent_(Length::Fixed())
    , tab_size_(TabSize(8))
    , text_emphasis_color_(StyleColorValue::CurrentColor())
    , hyphenate_limit_chars_(StyleHyphenateLimitChars())
{}

ComputedStyleBase::StyleMiscInherited2Data::StyleMiscInherited2Data()
    : text_emphasis_custom_mark_(AtomicString())
    , text_shadow_(nullptr)
    , text_underline_offset_(Length())
    , effective_zoom_(1.0f)
    , text_stroke_width_(0)
    , text_fill_color_(StyleColorValue::CurrentColor())
    , text_stroke_color_(StyleColorValue::CurrentColor())
{}

ComputedStyleBase::StyleMiscInheritedData::StyleMiscInheritedData()
    : misc_inherited_1_data_(std::make_shared<StyleMiscInherited1Data>())
    , misc_inherited_2_data_(std::make_shared<StyleMiscInherited2Data>())
    , text_underline_position_(static_cast<unsigned>(TextUnderlinePosition::kAuto))
    , line_break_(static_cast<unsigned>(LineBreak::kAuto))
    , text_align_last_(static_cast<unsigned>(ETextAlignLast::kAuto))
    , text_emphasis_mark_(static_cast<unsigned>(TextEmphasisMark::kNone))
    , text_emphasis_position_(static_cast<unsigned>(TextEmphasisPosition::kOverRight))
    , word_break_(static_cast<unsigned>(EWordBreak::kNormal))
    , hyphens_(static_cast<unsigned>(Hyphens::kManual))
    , overflow_wrap_(static_cast<unsigned>(EOverflowWrap::kNormal))
    , text_orientation_(static_cast<unsigned>(ETextOrientation::kMixed))
    , text_autospace_(static_cast<unsigned>(ETextAutospace::kNoAutospace))
    , text_combine_(static_cast<unsigned>(ETextCombine::kNone))
    , text_decoration_skip_ink_(static_cast<unsigned>(ETextDecorationSkipInk::kAuto))
    , text_emphasis_fill_(static_cast<unsigned>(TextEmphasisFill::kFilled))
{}

ComputedStyleBase::StyleBoxData::StyleBoxData()
    : vertical_align_length_(Length())
{}

ComputedStyleBase::StyleVisualData::StyleVisualData()
    : base_text_decoration_data_(nullptr)
    , text_decoration_line_(static_cast<unsigned>(TextDecorationLine::kNone))
{}

ComputedStyleBase::StyleMisc5Data::StyleMisc5Data()
    : text_decoration_color_(StyleColorValue::CurrentColor())
{}

ComputedStyleBase::StyleMisc6Data::StyleMisc6Data()
    : text_decoration_thickness_(TextDecorationThickness(Length::Auto()))
{}

ComputedStyleBase::StyleMiscData::StyleMiscData()
    : misc_5_data_(std::make_shared<StyleMisc5Data>())
    , misc_6_data_(std::make_shared<StyleMisc6Data>())
    , text_decoration_style_(static_cast<unsigned>(ETextDecorationStyle::kSolid))
{}

ComputedStyleBuilderBase::ComputedStyleBuilderBase(const ComputedStyleBase& style)
    : inherited_data_(style.inherited_data_)
    , misc_inherited_data_(style.misc_inherited_data_)
    , box_data_(style.box_data_)
    , visual_data_(style.visual_data_)
    , misc_data_(style.misc_data_)
    , data_(style.data_)
{}

ComputedStyleBuilderBase::ComputedStyleBuilderBase(
    const ComputedStyleBase& source_for_noninherited,
    const ComputedStyleBase& parent_style)
    : inherited_data_(parent_style.inherited_data_)
    , misc_inherited_data_(parent_style.misc_inherited_data_)
    , box_data_(source_for_noninherited.box_data_)
    , visual_data_(source_for_noninherited.visual_data_)
    , misc_data_(source_for_noninherited.misc_data_)
    , data_{
        parent_style.data_.text_align_,
        source_for_noninherited.data_.vertical_align_,
        parent_style.data_.text_transform_,
        source_for_noninherited.data_.unicode_bidi_,
        parent_style.data_.writing_mode_,
        parent_style.data_.text_wrap_style_,
        parent_style.data_.visibility_,
        parent_style.data_.white_space_collapse_,
        parent_style.data_.direction_,
        source_for_noninherited.data_.has_explicit_inheritance_,
        parent_style.data_.text_wrap_mode_
      }
{}

} // namespace bkfont
