// Generated by tools/style/make_computed_style_base.py from
// blink/renderer/core/css/css_properties.json5 and
// blink/renderer/core/style/computed_style_extra_fields.json5. Do not edit.
// Copyright 2016 The Chromium Authors
// Use of this source code is governed by a BSD-style license in LICENSE.
#pragma once

#include <memory>
#include <utility>

#include "base/memory/values_equivalent.h"
#include "base/text/atomic_string.h"
#include "font/font.h"
#include "geometry/length.h"
#include "layout/layout_unit.h"
#include "paint/platform_paint.h"
#include "style/applied_text_decoration.h"
#include "style/computed_style_base_constants.h"
#include "style/computed_style_constants.h"
#include "style/shadow_list.h"
#include "style/style_color.h"
#include "style/style_hyphenate_limit_chars.h"
#include "style/text_decoration_thickness.h"
#include "style/white_space.h"
#include "text/tab_size.h"
#include "text/text_direction.h"
#include "text/unicode_bidi.h"
#include "text/writing_mode.h"

namespace bkfont {

class ComputedStyleBuilderBase;

// The generated portion of ComputedStyle. Fields are stored in a tree
// of groups; styles and builders share a group until one of them
// writes to it. A published ComputedStyleBase is never written.
class ComputedStyleBase {
public:
  bool IndependentInheritedEqual(const ComputedStyleBase& o) const {
    return true;
  }

  bool NonIndependentInheritedEqual(const ComputedStyleBase& o) const {
    return base::ValuesEquivalent(inherited_data_, o.inherited_data_)
        && base::ValuesEquivalent(misc_inherited_data_, o.misc_inherited_data_)
        && data_.text_align_ == o.data_.text_align_
        && data_.text_transform_ == o.data_.text_transform_
        && data_.writing_mode_ == o.data_.writing_mode_
        && data_.text_wrap_style_ == o.data_.text_wrap_style_
        && data_.visibility_ == o.data_.visibility_
        && data_.white_space_collapse_ == o.data_.white_space_collapse_
        && data_.direction_ == o.data_.direction_
        && data_.text_wrap_mode_ == o.data_.text_wrap_mode_;
  }

  bool InheritedEqual(const ComputedStyleBase& o) const {
    return IndependentInheritedEqual(o) && NonIndependentInheritedEqual(o);
  }

  bool NonInheritedEqual(const ComputedStyleBase& o) const {
    return base::ValuesEquivalent(box_data_, o.box_data_)
        && base::ValuesEquivalent(visual_data_, o.visual_data_)
        && base::ValuesEquivalent(misc_data_, o.misc_data_)
        && data_.vertical_align_ == o.data_.vertical_align_
        && data_.unicode_bidi_ == o.data_.unicode_bidi_
        && data_.has_explicit_inheritance_ == o.data_.has_explicit_inheritance_;
  }

  // BaseTextDecorationData
  const AppliedTextDecorationVector* BaseTextDecorationData() const {
    return visual_data_->base_text_decoration_data_.get();
  }
  const std::shared_ptr<const AppliedTextDecorationVector>& SharedBaseTextDecorationData() const {
    return visual_data_->base_text_decoration_data_;
  }

  // direction
  TextDirection Direction() const {
    return static_cast<TextDirection>(data_.direction_);
  }

  // EffectiveZoom
  float EffectiveZoom() const {
    return misc_inherited_data_->misc_inherited_2_data_->effective_zoom_;
  }

  // HasExplicitInheritance
  bool HasExplicitInheritance() const {
    return static_cast<bool>(data_.has_explicit_inheritance_);
  }

  // hyphenate-limit-chars
  const StyleHyphenateLimitChars& HyphenateLimitChars() const {
    return misc_inherited_data_->misc_inherited_1_data_->hyphenate_limit_chars_;
  }

  // hyphenate-character
  const AtomicString& HyphenationString() const {
    return misc_inherited_data_->misc_inherited_1_data_->hyphenation_string_;
  }

  // hyphens
  Hyphens GetHyphens() const {
    return static_cast<Hyphens>(misc_inherited_data_->hyphens_);
  }

  // -internal-legacy-baseline-shift
  LayoutUnit LegacyBaselineShift() const {
    return inherited_data_->legacy_baseline_shift_;
  }

  // -internal-legacy-paint
  const PlatformPaint& LegacyPaint() const {
    return inherited_data_->legacy_paint_;
  }

  // -webkit-line-break
  LineBreak GetLineBreak() const {
    return static_cast<LineBreak>(misc_inherited_data_->line_break_);
  }

  // overflow-wrap
  EOverflowWrap OverflowWrap() const {
    return static_cast<EOverflowWrap>(misc_inherited_data_->overflow_wrap_);
  }

  // tab-size
  const TabSize& GetTabSize() const {
    return misc_inherited_data_->misc_inherited_1_data_->tab_size_;
  }

  // text-align
  ETextAlign GetTextAlign() const {
    return static_cast<ETextAlign>(data_.text_align_);
  }

  // text-align-last
  ETextAlignLast TextAlignLast() const {
    return static_cast<ETextAlignLast>(misc_inherited_data_->text_align_last_);
  }

  // text-autospace
  ETextAutospace TextAutospace() const {
    return static_cast<ETextAutospace>(misc_inherited_data_->text_autospace_);
  }

  // text-combine-upright
  ETextCombine TextCombine() const {
    return static_cast<ETextCombine>(misc_inherited_data_->text_combine_);
  }

  // text-decoration-line
  TextDecorationLine GetTextDecorationLine() const {
    return static_cast<TextDecorationLine>(visual_data_->text_decoration_line_);
  }

  // text-decoration-skip-ink
  ETextDecorationSkipInk TextDecorationSkipInk() const {
    return static_cast<ETextDecorationSkipInk>(misc_inherited_data_->text_decoration_skip_ink_);
  }

  // text-decoration-style
  ETextDecorationStyle TextDecorationStyle() const {
    return static_cast<ETextDecorationStyle>(misc_data_->text_decoration_style_);
  }

  // text-decoration-thickness
  const TextDecorationThickness& GetTextDecorationThickness() const {
    return misc_data_->misc_6_data_->text_decoration_thickness_;
  }

  // TextEmphasisCustomMark
  const AtomicString& TextEmphasisCustomMark() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_emphasis_custom_mark_;
  }

  // TextEmphasisFill
  TextEmphasisFill GetTextEmphasisFill() const {
    return static_cast<TextEmphasisFill>(misc_inherited_data_->text_emphasis_fill_);
  }

  // text-emphasis-position
  TextEmphasisPosition GetTextEmphasisPosition() const {
    return static_cast<TextEmphasisPosition>(misc_inherited_data_->text_emphasis_position_);
  }

  // text-indent
  const Length& TextIndent() const {
    return misc_inherited_data_->misc_inherited_1_data_->text_indent_;
  }

  // text-orientation
  ETextOrientation GetTextOrientation() const {
    return static_cast<ETextOrientation>(misc_inherited_data_->text_orientation_);
  }

  // text-shadow
  const ShadowList* TextShadow() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_shadow_.get();
  }
  const std::shared_ptr<const ShadowList>& SharedTextShadow() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_shadow_;
  }

  // -webkit-text-stroke-width
  float TextStrokeWidth() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_stroke_width_;
  }

  // text-transform
  ETextTransform TextTransform() const {
    return static_cast<ETextTransform>(data_.text_transform_);
  }

  // text-underline-offset
  const Length& TextUnderlineOffset() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_underline_offset_;
  }

  // text-underline-position
  TextUnderlinePosition GetTextUnderlinePosition() const {
    return static_cast<TextUnderlinePosition>(misc_inherited_data_->text_underline_position_);
  }

  // text-wrap-mode
  TextWrapMode GetTextWrapMode() const {
    return static_cast<TextWrapMode>(data_.text_wrap_mode_);
  }

  // text-wrap-style
  TextWrapStyle GetTextWrapStyle() const {
    return static_cast<TextWrapStyle>(data_.text_wrap_style_);
  }

  // unicode-bidi
  UnicodeBidi GetUnicodeBidi() const {
    return static_cast<UnicodeBidi>(data_.unicode_bidi_);
  }

  // VerticalAlignLength
  const Length& GetVerticalAlignLength() const {
    return box_data_->vertical_align_length_;
  }

  // visibility
  EVisibility Visibility() const {
    return static_cast<EVisibility>(data_.visibility_);
  }

  // white-space-collapse
  WhiteSpaceCollapse GetWhiteSpaceCollapse() const {
    return static_cast<WhiteSpaceCollapse>(data_.white_space_collapse_);
  }

  // word-break
  EWordBreak WordBreak() const {
    return static_cast<EWordBreak>(misc_inherited_data_->word_break_);
  }

  // writing-mode
  WritingMode GetWritingMode() const {
    return static_cast<WritingMode>(data_.writing_mode_);
  }

  class StyleInheritedData {
  public:
    StyleInheritedData();
    StyleInheritedData(const StyleInheritedData&) = default;

    bool operator==(const StyleInheritedData& other) const {
      return true
          && font_ == other.font_
          && legacy_paint_ == other.legacy_paint_
          && line_height_ == other.line_height_
          && legacy_baseline_shift_ == other.legacy_baseline_shift_;
    }
    bool operator!=(const StyleInheritedData& other) const { return !(*this == other); }

    Font font_;
    PlatformPaint legacy_paint_;
    Length line_height_;
    LayoutUnit legacy_baseline_shift_;
  };

  class StyleMiscInherited1Data {
  public:
    StyleMiscInherited1Data();
    StyleMiscInherited1Data(const StyleMiscInherited1Data&) = default;

    bool operator==(const StyleMiscInherited1Data& other) const {
      return true
          && hyphenation_string_ == other.hyphenation_string_
          && text_indent_ == other.text_indent_
          && tab_size_ == other.tab_size_
          && text_emphasis_color_ == other.text_emphasis_color_
          && hyphenate_limit_chars_ == other.hyphenate_limit_chars_;
    }
    bool operator!=(const StyleMiscInherited1Data& other) const { return !(*this == other); }

    AtomicString hyphenation_string_;
    Length text_indent_;
    TabSize tab_size_;
    StyleColorValue text_emphasis_color_;
    StyleHyphenateLimitChars hyphenate_limit_chars_;
  };

  class StyleMiscInherited2Data {
  public:
    StyleMiscInherited2Data();
    StyleMiscInherited2Data(const StyleMiscInherited2Data&) = default;

    bool operator==(const StyleMiscInherited2Data& other) const {
      return true
          && text_emphasis_custom_mark_ == other.text_emphasis_custom_mark_
          && base::ValuesEquivalent(text_shadow_, other.text_shadow_)
          && text_underline_offset_ == other.text_underline_offset_
          && effective_zoom_ == other.effective_zoom_
          && text_stroke_width_ == other.text_stroke_width_
          && text_fill_color_ == other.text_fill_color_
          && text_stroke_color_ == other.text_stroke_color_;
    }
    bool operator!=(const StyleMiscInherited2Data& other) const { return !(*this == other); }

    AtomicString text_emphasis_custom_mark_;
    std::shared_ptr<const ShadowList> text_shadow_;
    Length text_underline_offset_;
    float effective_zoom_;
    float text_stroke_width_;
    StyleColorValue text_fill_color_;
    StyleColorValue text_stroke_color_;
  };

  class StyleMiscInheritedData {
  public:
    StyleMiscInheritedData();
    StyleMiscInheritedData(const StyleMiscInheritedData&) = default;

    bool operator==(const StyleMiscInheritedData& other) const {
      return true
          && base::ValuesEquivalent(misc_inherited_1_data_, other.misc_inherited_1_data_)
          && base::ValuesEquivalent(misc_inherited_2_data_, other.misc_inherited_2_data_)
          && text_underline_position_ == other.text_underline_position_
          && line_break_ == other.line_break_
          && text_align_last_ == other.text_align_last_
          && text_emphasis_mark_ == other.text_emphasis_mark_
          && text_emphasis_position_ == other.text_emphasis_position_
          && word_break_ == other.word_break_
          && hyphens_ == other.hyphens_
          && overflow_wrap_ == other.overflow_wrap_
          && text_orientation_ == other.text_orientation_
          && text_autospace_ == other.text_autospace_
          && text_combine_ == other.text_combine_
          && text_decoration_skip_ink_ == other.text_decoration_skip_ink_
          && text_emphasis_fill_ == other.text_emphasis_fill_;
    }
    bool operator!=(const StyleMiscInheritedData& other) const { return !(*this == other); }

    std::shared_ptr<const StyleMiscInherited1Data> misc_inherited_1_data_;
    std::shared_ptr<const StyleMiscInherited2Data> misc_inherited_2_data_;
    unsigned text_underline_position_ : 4; // TextUnderlinePosition
    unsigned line_break_ : 3; // LineBreak
    unsigned text_align_last_ : 3; // ETextAlignLast
    unsigned text_emphasis_mark_ : 3; // TextEmphasisMark
    unsigned text_emphasis_position_ : 3; // TextEmphasisPosition
    unsigned word_break_ : 3; // EWordBreak
    unsigned hyphens_ : 2; // Hyphens
    unsigned overflow_wrap_ : 2; // EOverflowWrap
    unsigned text_orientation_ : 2; // ETextOrientation
    unsigned text_autospace_ : 1; // ETextAutospace
    unsigned text_combine_ : 1; // ETextCombine
    unsigned text_decoration_skip_ink_ : 1; // ETextDecorationSkipInk
    unsigned text_emphasis_fill_ : 1; // TextEmphasisFill
  };

  class StyleBoxData {
  public:
    StyleBoxData();
    StyleBoxData(const StyleBoxData&) = default;

    bool operator==(const StyleBoxData& other) const {
      return true
          && vertical_align_length_ == other.vertical_align_length_;
    }
    bool operator!=(const StyleBoxData& other) const { return !(*this == other); }

    Length vertical_align_length_;
  };

  class StyleVisualData {
  public:
    StyleVisualData();
    StyleVisualData(const StyleVisualData&) = default;

    bool operator==(const StyleVisualData& other) const {
      return true
          && base::ValuesEquivalent(base_text_decoration_data_, other.base_text_decoration_data_)
          && text_decoration_line_ == other.text_decoration_line_;
    }
    bool operator!=(const StyleVisualData& other) const { return !(*this == other); }

    std::shared_ptr<const AppliedTextDecorationVector> base_text_decoration_data_;
    unsigned text_decoration_line_ : 6; // TextDecorationLine
  };

  class StyleMisc5Data {
  public:
    StyleMisc5Data();
    StyleMisc5Data(const StyleMisc5Data&) = default;

    bool operator==(const StyleMisc5Data& other) const {
      return true
          && text_decoration_color_ == other.text_decoration_color_;
    }
    bool operator!=(const StyleMisc5Data& other) const { return !(*this == other); }

    StyleColorValue text_decoration_color_;
  };

  class StyleMisc6Data {
  public:
    StyleMisc6Data();
    StyleMisc6Data(const StyleMisc6Data&) = default;

    bool operator==(const StyleMisc6Data& other) const {
      return true
          && text_decoration_thickness_ == other.text_decoration_thickness_;
    }
    bool operator!=(const StyleMisc6Data& other) const { return !(*this == other); }

    TextDecorationThickness text_decoration_thickness_;
  };

  class StyleMiscData {
  public:
    StyleMiscData();
    StyleMiscData(const StyleMiscData&) = default;

    bool operator==(const StyleMiscData& other) const {
      return true
          && base::ValuesEquivalent(misc_5_data_, other.misc_5_data_)
          && base::ValuesEquivalent(misc_6_data_, other.misc_6_data_)
          && text_decoration_style_ == other.text_decoration_style_;
    }
    bool operator!=(const StyleMiscData& other) const { return !(*this == other); }

    std::shared_ptr<const StyleMisc5Data> misc_5_data_;
    std::shared_ptr<const StyleMisc6Data> misc_6_data_;
    unsigned text_decoration_style_ : 3; // ETextDecorationStyle
  };

protected:
  ComputedStyleBase();
  ComputedStyleBase(const ComputedStyleBase&) = default;
  ComputedStyleBase& operator=(const ComputedStyleBase&) = delete;
  // Publishes the builder's groups and resets its access flags.
  explicit ComputedStyleBase(const ComputedStyleBuilderBase&);

  // font
  const Font& FontInternal() const {
    return inherited_data_->font_;
  }

  // line-height
  const Length& LineHeightInternal() const {
    return inherited_data_->line_height_;
  }

  // text-decoration-color
  const StyleColorValue& TextDecorationColor() const {
    return misc_data_->misc_5_data_->text_decoration_color_;
  }

  // text-emphasis-color
  const StyleColorValue& TextEmphasisColor() const {
    return misc_inherited_data_->misc_inherited_1_data_->text_emphasis_color_;
  }

  // TextEmphasisMark
  TextEmphasisMark TextEmphasisMarkInternal() const {
    return static_cast<TextEmphasisMark>(misc_inherited_data_->text_emphasis_mark_);
  }

  // -webkit-text-fill-color
  const StyleColorValue& TextFillColor() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_fill_color_;
  }

  // -webkit-text-stroke-color
  const StyleColorValue& TextStrokeColor() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_stroke_color_;
  }

  // VerticalAlign
  unsigned VerticalAlignInternal() const {
    return static_cast<unsigned>(data_.vertical_align_);
  }

  struct Data {
    unsigned text_align_ : 4; // ETextAlign
    unsigned vertical_align_ : 4; // unsigned
    unsigned text_transform_ : 3; // ETextTransform
    unsigned unicode_bidi_ : 3; // UnicodeBidi
    unsigned writing_mode_ : 3; // WritingMode
    unsigned text_wrap_style_ : 2; // TextWrapStyle
    unsigned visibility_ : 2; // EVisibility
    unsigned white_space_collapse_ : 2; // WhiteSpaceCollapse
    unsigned direction_ : 1; // TextDirection
    unsigned has_explicit_inheritance_ : 1; // bool
    unsigned text_wrap_mode_ : 1; // TextWrapMode
  };

private:
  friend class ComputedStyleBuilderBase;

  std::shared_ptr<const StyleInheritedData> inherited_data_;
  std::shared_ptr<const StyleMiscInheritedData> misc_inherited_data_;
  std::shared_ptr<const StyleBoxData> box_data_;
  std::shared_ptr<const StyleVisualData> visual_data_;
  std::shared_ptr<const StyleMiscData> misc_data_;
  Data data_;
};

class ComputedStyleBuilderBase {
public:
  // BaseTextDecorationData
  const AppliedTextDecorationVector* BaseTextDecorationData() const {
    return visual_data_->base_text_decoration_data_.get();
  }
  const std::shared_ptr<const AppliedTextDecorationVector>& SharedBaseTextDecorationData() const {
    return visual_data_->base_text_decoration_data_;
  }
  void SetBaseTextDecorationData(std::shared_ptr<const AppliedTextDecorationVector> v) {
    if (!(visual_data_->base_text_decoration_data_ == v))
      Access(visual_data_, access_.visual_data_)->base_text_decoration_data_ = std::move(v);
  }
  void ResetBaseTextDecorationData() {
    Access(visual_data_, access_.visual_data_)->base_text_decoration_data_ = nullptr;
  }

  // direction
  TextDirection Direction() const {
    return static_cast<TextDirection>(data_.direction_);
  }
  void SetDirection(TextDirection v) {
    data_.direction_ = static_cast<unsigned>(v);
  }
  void ResetDirection() {
    data_.direction_ = static_cast<unsigned>(TextDirection::kLtr);
  }

  // EffectiveZoom
  float EffectiveZoom() const {
    return misc_inherited_data_->misc_inherited_2_data_->effective_zoom_;
  }
  void ResetEffectiveZoom() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->effective_zoom_ = 1.0f;
  }

  // font
  void SetFont(const Font& v) {
    if (!(inherited_data_->font_ == v))
      Access(inherited_data_, access_.inherited_data_)->font_ = v;
  }
  void SetFont(Font&& v) {
    if (!(inherited_data_->font_ == v))
      Access(inherited_data_, access_.inherited_data_)->font_ = std::move(v);
  }
  void ResetFont() {
    Access(inherited_data_, access_.inherited_data_)->font_ = Font();
  }

  // HasExplicitInheritance
  bool HasExplicitInheritance() const {
    return static_cast<bool>(data_.has_explicit_inheritance_);
  }
  void SetHasExplicitInheritance() {
    data_.has_explicit_inheritance_ = static_cast<unsigned>(true);
  }

  // hyphenate-limit-chars
  const StyleHyphenateLimitChars& HyphenateLimitChars() const {
    return misc_inherited_data_->misc_inherited_1_data_->hyphenate_limit_chars_;
  }
  void SetHyphenateLimitChars(const StyleHyphenateLimitChars& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->hyphenate_limit_chars_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenate_limit_chars_ = v;
  }
  void SetHyphenateLimitChars(StyleHyphenateLimitChars&& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->hyphenate_limit_chars_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenate_limit_chars_ = std::move(v);
  }
  void ResetHyphenateLimitChars() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenate_limit_chars_ = StyleHyphenateLimitChars();
  }

  // hyphenate-character
  const AtomicString& HyphenationString() const {
    return misc_inherited_data_->misc_inherited_1_data_->hyphenation_string_;
  }
  void SetHyphenationString(const AtomicString& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->hyphenation_string_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenation_string_ = v;
  }
  void SetHyphenationString(AtomicString&& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->hyphenation_string_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenation_string_ = std::move(v);
  }
  void ResetHyphenationString() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenation_string_ = AtomicString();
  }

  // hyphens
  Hyphens GetHyphens() const {
    return static_cast<Hyphens>(misc_inherited_data_->hyphens_);
  }
  void SetHyphens(Hyphens v) {
    if (!(misc_inherited_data_->hyphens_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->hyphens_ = static_cast<unsigned>(v);
  }
  void ResetHyphens() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->hyphens_ = static_cast<unsigned>(Hyphens::kManual);
  }

  // -internal-legacy-baseline-shift
  LayoutUnit LegacyBaselineShift() const {
    return inherited_data_->legacy_baseline_shift_;
  }
  void SetLegacyBaselineShift(LayoutUnit v) {
    if (!(inherited_data_->legacy_baseline_shift_ == v))
      Access(inherited_data_, access_.inherited_data_)->legacy_baseline_shift_ = v;
  }
  void ResetLegacyBaselineShift() {
    Access(inherited_data_, access_.inherited_data_)->legacy_baseline_shift_ = LayoutUnit();
  }

  // -internal-legacy-paint
  const PlatformPaint& LegacyPaint() const {
    return inherited_data_->legacy_paint_;
  }
  void SetLegacyPaint(const PlatformPaint& v) {
    if (!(inherited_data_->legacy_paint_ == v))
      Access(inherited_data_, access_.inherited_data_)->legacy_paint_ = v;
  }
  void SetLegacyPaint(PlatformPaint&& v) {
    if (!(inherited_data_->legacy_paint_ == v))
      Access(inherited_data_, access_.inherited_data_)->legacy_paint_ = std::move(v);
  }
  void ResetLegacyPaint() {
    Access(inherited_data_, access_.inherited_data_)->legacy_paint_ = PlatformPaint();
  }

  // -webkit-line-break
  LineBreak GetLineBreak() const {
    return static_cast<LineBreak>(misc_inherited_data_->line_break_);
  }
  void SetLineBreak(LineBreak v) {
    if (!(misc_inherited_data_->line_break_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->line_break_ = static_cast<unsigned>(v);
  }
  void ResetLineBreak() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->line_break_ = static_cast<unsigned>(LineBreak::kAuto);
  }

  // line-height
  void SetLineHeight(const Length& v) {
    if (!(inherited_data_->line_height_ == v))
      Access(inherited_data_, access_.inherited_data_)->line_height_ = v;
  }
  void SetLineHeight(Length&& v) {
    if (!(inherited_data_->line_height_ == v))
      Access(inherited_data_, access_.inherited_data_)->line_height_ = std::move(v);
  }
  void ResetLineHeight() {
    Access(inherited_data_, access_.inherited_data_)->line_height_ = Length::Auto();
  }

  // overflow-wrap
  EOverflowWrap OverflowWrap() const {
    return static_cast<EOverflowWrap>(misc_inherited_data_->overflow_wrap_);
  }
  void SetOverflowWrap(EOverflowWrap v) {
    if (!(misc_inherited_data_->overflow_wrap_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->overflow_wrap_ = static_cast<unsigned>(v);
  }
  void ResetOverflowWrap() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->overflow_wrap_ = static_cast<unsigned>(EOverflowWrap::kNormal);
  }

  // tab-size
  const TabSize& GetTabSize() const {
    return misc_inherited_data_->misc_inherited_1_data_->tab_size_;
  }
  void ResetTabSize() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->tab_size_ = TabSize(8);
  }

  // text-align
  ETextAlign GetTextAlign() const {
    return static_cast<ETextAlign>(data_.text_align_);
  }
  void SetTextAlign(ETextAlign v) {
    data_.text_align_ = static_cast<unsigned>(v);
  }
  void ResetTextAlign() {
    data_.text_align_ = static_cast<unsigned>(ETextAlign::kStart);
  }

  // text-align-last
  ETextAlignLast TextAlignLast() const {
    return static_cast<ETextAlignLast>(misc_inherited_data_->text_align_last_);
  }
  void SetTextAlignLast(ETextAlignLast v) {
    if (!(misc_inherited_data_->text_align_last_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_align_last_ = static_cast<unsigned>(v);
  }
  void ResetTextAlignLast() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_align_last_ = static_cast<unsigned>(ETextAlignLast::kAuto);
  }

  // text-autospace
  ETextAutospace TextAutospace() const {
    return static_cast<ETextAutospace>(misc_inherited_data_->text_autospace_);
  }
  void SetTextAutospace(ETextAutospace v) {
    if (!(misc_inherited_data_->text_autospace_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_autospace_ = static_cast<unsigned>(v);
  }
  void ResetTextAutospace() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_autospace_ = static_cast<unsigned>(ETextAutospace::kNoAutospace);
  }

  // text-combine-upright
  ETextCombine TextCombine() const {
    return static_cast<ETextCombine>(misc_inherited_data_->text_combine_);
  }
  void SetTextCombine(ETextCombine v) {
    if (!(misc_inherited_data_->text_combine_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_combine_ = static_cast<unsigned>(v);
  }
  void ResetTextCombine() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_combine_ = static_cast<unsigned>(ETextCombine::kNone);
  }

  // text-decoration-color
  void SetTextDecorationColor(const StyleColorValue& v) {
    if (!(misc_data_->misc_5_data_->text_decoration_color_ == v))
      Access(Access(misc_data_, access_.misc_data_)->misc_5_data_, access_.misc_5_data_)->text_decoration_color_ = v;
  }
  void SetTextDecorationColor(StyleColorValue&& v) {
    if (!(misc_data_->misc_5_data_->text_decoration_color_ == v))
      Access(Access(misc_data_, access_.misc_data_)->misc_5_data_, access_.misc_5_data_)->text_decoration_color_ = std::move(v);
  }
  void ResetTextDecorationColor() {
    Access(Access(misc_data_, access_.misc_data_)->misc_5_data_, access_.misc_5_data_)->text_decoration_color_ = StyleColorValue::CurrentColor();
  }

  // text-decoration-line
  TextDecorationLine GetTextDecorationLine() const {
    return static_cast<TextDecorationLine>(visual_data_->text_decoration_line_);
  }
  void SetTextDecorationLine(TextDecorationLine v) {
    if (!(visual_data_->text_decoration_line_ == static_cast<unsigned>(v)))
      Access(visual_data_, access_.visual_data_)->text_decoration_line_ = static_cast<unsigned>(v);
  }
  void ResetTextDecorationLine() {
    Access(visual_data_, access_.visual_data_)->text_decoration_line_ = static_cast<unsigned>(TextDecorationLine::kNone);
  }

  // text-decoration-skip-ink
  ETextDecorationSkipInk TextDecorationSkipInk() const {
    return static_cast<ETextDecorationSkipInk>(misc_inherited_data_->text_decoration_skip_ink_);
  }
  void SetTextDecorationSkipInk(ETextDecorationSkipInk v) {
    if (!(misc_inherited_data_->text_decoration_skip_ink_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_decoration_skip_ink_ = static_cast<unsigned>(v);
  }
  void ResetTextDecorationSkipInk() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_decoration_skip_ink_ = static_cast<unsigned>(ETextDecorationSkipInk::kAuto);
  }

  // text-decoration-style
  ETextDecorationStyle TextDecorationStyle() const {
    return static_cast<ETextDecorationStyle>(misc_data_->text_decoration_style_);
  }
  void SetTextDecorationStyle(ETextDecorationStyle v) {
    if (!(misc_data_->text_decoration_style_ == static_cast<unsigned>(v)))
      Access(misc_data_, access_.misc_data_)->text_decoration_style_ = static_cast<unsigned>(v);
  }
  void ResetTextDecorationStyle() {
    Access(misc_data_, access_.misc_data_)->text_decoration_style_ = static_cast<unsigned>(ETextDecorationStyle::kSolid);
  }

  // text-decoration-thickness
  const TextDecorationThickness& GetTextDecorationThickness() const {
    return misc_data_->misc_6_data_->text_decoration_thickness_;
  }
  void SetTextDecorationThickness(const TextDecorationThickness& v) {
    if (!(misc_data_->misc_6_data_->text_decoration_thickness_ == v))
      Access(Access(misc_data_, access_.misc_data_)->misc_6_data_, access_.misc_6_data_)->text_decoration_thickness_ = v;
  }
  void SetTextDecorationThickness(TextDecorationThickness&& v) {
    if (!(misc_data_->misc_6_data_->text_decoration_thickness_ == v))
      Access(Access(misc_data_, access_.misc_data_)->misc_6_data_, access_.misc_6_data_)->text_decoration_thickness_ = std::move(v);
  }
  void ResetTextDecorationThickness() {
    Access(Access(misc_data_, access_.misc_data_)->misc_6_data_, access_.misc_6_data_)->text_decoration_thickness_ = TextDecorationThickness(Length::Auto());
  }

  // text-emphasis-color
  void SetTextEmphasisColor(const StyleColorValue& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->text_emphasis_color_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_emphasis_color_ = v;
  }
  void SetTextEmphasisColor(StyleColorValue&& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->text_emphasis_color_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_emphasis_color_ = std::move(v);
  }
  void ResetTextEmphasisColor() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_emphasis_color_ = StyleColorValue::CurrentColor();
  }

  // TextEmphasisCustomMark
  const AtomicString& TextEmphasisCustomMark() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_emphasis_custom_mark_;
  }
  void SetTextEmphasisCustomMark(const AtomicString& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_emphasis_custom_mark_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_emphasis_custom_mark_ = v;
  }
  void SetTextEmphasisCustomMark(AtomicString&& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_emphasis_custom_mark_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_emphasis_custom_mark_ = std::move(v);
  }
  void ResetTextEmphasisCustomMark() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_emphasis_custom_mark_ = AtomicString();
  }

  // TextEmphasisFill
  TextEmphasisFill GetTextEmphasisFill() const {
    return static_cast<TextEmphasisFill>(misc_inherited_data_->text_emphasis_fill_);
  }
  void SetTextEmphasisFill(TextEmphasisFill v) {
    if (!(misc_inherited_data_->text_emphasis_fill_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_emphasis_fill_ = static_cast<unsigned>(v);
  }
  void ResetTextEmphasisFill() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_emphasis_fill_ = static_cast<unsigned>(TextEmphasisFill::kFilled);
  }

  // TextEmphasisMark
  void SetTextEmphasisMark(TextEmphasisMark v) {
    if (!(misc_inherited_data_->text_emphasis_mark_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_emphasis_mark_ = static_cast<unsigned>(v);
  }
  void ResetTextEmphasisMark() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_emphasis_mark_ = static_cast<unsigned>(TextEmphasisMark::kNone);
  }

  // text-emphasis-position
  TextEmphasisPosition GetTextEmphasisPosition() const {
    return static_cast<TextEmphasisPosition>(misc_inherited_data_->text_emphasis_position_);
  }
  void SetTextEmphasisPosition(TextEmphasisPosition v) {
    if (!(misc_inherited_data_->text_emphasis_position_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_emphasis_position_ = static_cast<unsigned>(v);
  }
  void ResetTextEmphasisPosition() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_emphasis_position_ = static_cast<unsigned>(TextEmphasisPosition::kOverRight);
  }

  // -webkit-text-fill-color
  void SetTextFillColor(const StyleColorValue& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_fill_color_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_fill_color_ = v;
  }
  void SetTextFillColor(StyleColorValue&& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_fill_color_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_fill_color_ = std::move(v);
  }
  void ResetTextFillColor() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_fill_color_ = StyleColorValue::CurrentColor();
  }

  // text-indent
  const Length& TextIndent() const {
    return misc_inherited_data_->misc_inherited_1_data_->text_indent_;
  }
  void SetTextIndent(const Length& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->text_indent_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_indent_ = v;
  }
  void SetTextIndent(Length&& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->text_indent_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_indent_ = std::move(v);
  }
  void ResetTextIndent() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_indent_ = Length::Fixed();
  }

  // text-orientation
  ETextOrientation GetTextOrientation() const {
    return static_cast<ETextOrientation>(misc_inherited_data_->text_orientation_);
  }
  void SetTextOrientation(ETextOrientation v) {
    if (!(misc_inherited_data_->text_orientation_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_orientation_ = static_cast<unsigned>(v);
  }
  void ResetTextOrientation() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_orientation_ = static_cast<unsigned>(ETextOrientation::kMixed);
  }

  // text-shadow
  const ShadowList* TextShadow() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_shadow_.get();
  }
  const std::shared_ptr<const ShadowList>& SharedTextShadow() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_shadow_;
  }
  void SetTextShadow(std::shared_ptr<const ShadowList> v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_shadow_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_shadow_ = std::move(v);
  }
  void ResetTextShadow() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_shadow_ = nullptr;
  }

  // -webkit-text-stroke-color
  void SetTextStrokeColor(const StyleColorValue& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_stroke_color_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_stroke_color_ = v;
  }
  void SetTextStrokeColor(StyleColorValue&& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_stroke_color_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_stroke_color_ = std::move(v);
  }
  void ResetTextStrokeColor() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_stroke_color_ = StyleColorValue::CurrentColor();
  }

  // -webkit-text-stroke-width
  float TextStrokeWidth() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_stroke_width_;
  }
  void SetTextStrokeWidth(float v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_stroke_width_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_stroke_width_ = v;
  }
  void ResetTextStrokeWidth() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_stroke_width_ = 0;
  }

  // text-transform
  ETextTransform TextTransform() const {
    return static_cast<ETextTransform>(data_.text_transform_);
  }
  void SetTextTransform(ETextTransform v) {
    data_.text_transform_ = static_cast<unsigned>(v);
  }
  void ResetTextTransform() {
    data_.text_transform_ = static_cast<unsigned>(ETextTransform::kNone);
  }

  // text-underline-offset
  const Length& TextUnderlineOffset() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_underline_offset_;
  }
  void SetTextUnderlineOffset(const Length& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_underline_offset_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_underline_offset_ = v;
  }
  void SetTextUnderlineOffset(Length&& v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->text_underline_offset_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_underline_offset_ = std::move(v);
  }
  void ResetTextUnderlineOffset() {
    Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_underline_offset_ = Length();
  }

  // text-underline-position
  TextUnderlinePosition GetTextUnderlinePosition() const {
    return static_cast<TextUnderlinePosition>(misc_inherited_data_->text_underline_position_);
  }
  void SetTextUnderlinePosition(TextUnderlinePosition v) {
    if (!(misc_inherited_data_->text_underline_position_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->text_underline_position_ = static_cast<unsigned>(v);
  }
  void ResetTextUnderlinePosition() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->text_underline_position_ = static_cast<unsigned>(TextUnderlinePosition::kAuto);
  }

  // text-wrap-mode
  TextWrapMode GetTextWrapMode() const {
    return static_cast<TextWrapMode>(data_.text_wrap_mode_);
  }
  void SetTextWrapMode(TextWrapMode v) {
    data_.text_wrap_mode_ = static_cast<unsigned>(v);
  }
  void ResetTextWrapMode() {
    data_.text_wrap_mode_ = static_cast<unsigned>(TextWrapMode::kWrap);
  }

  // text-wrap-style
  TextWrapStyle GetTextWrapStyle() const {
    return static_cast<TextWrapStyle>(data_.text_wrap_style_);
  }
  void SetTextWrapStyle(TextWrapStyle v) {
    data_.text_wrap_style_ = static_cast<unsigned>(v);
  }
  void ResetTextWrapStyle() {
    data_.text_wrap_style_ = static_cast<unsigned>(TextWrapStyle::kAuto);
  }

  // unicode-bidi
  UnicodeBidi GetUnicodeBidi() const {
    return static_cast<UnicodeBidi>(data_.unicode_bidi_);
  }
  void SetUnicodeBidi(UnicodeBidi v) {
    data_.unicode_bidi_ = static_cast<unsigned>(v);
  }
  void ResetUnicodeBidi() {
    data_.unicode_bidi_ = static_cast<unsigned>(UnicodeBidi::kNormal);
  }

  // VerticalAlign
  void ResetVerticalAlign() {
    data_.vertical_align_ = static_cast<unsigned>(static_cast<unsigned>(EVerticalAlign::kBaseline));
  }

  // VerticalAlignLength
  const Length& GetVerticalAlignLength() const {
    return box_data_->vertical_align_length_;
  }
  void ResetVerticalAlignLength() {
    Access(box_data_, access_.box_data_)->vertical_align_length_ = Length();
  }

  // visibility
  EVisibility Visibility() const {
    return static_cast<EVisibility>(data_.visibility_);
  }
  void SetVisibility(EVisibility v) {
    data_.visibility_ = static_cast<unsigned>(v);
  }
  void ResetVisibility() {
    data_.visibility_ = static_cast<unsigned>(EVisibility::kVisible);
  }

  // white-space-collapse
  WhiteSpaceCollapse GetWhiteSpaceCollapse() const {
    return static_cast<WhiteSpaceCollapse>(data_.white_space_collapse_);
  }
  void SetWhiteSpaceCollapse(WhiteSpaceCollapse v) {
    data_.white_space_collapse_ = static_cast<unsigned>(v);
  }
  void ResetWhiteSpaceCollapse() {
    data_.white_space_collapse_ = static_cast<unsigned>(WhiteSpaceCollapse::kCollapse);
  }

  // word-break
  EWordBreak WordBreak() const {
    return static_cast<EWordBreak>(misc_inherited_data_->word_break_);
  }
  void SetWordBreak(EWordBreak v) {
    if (!(misc_inherited_data_->word_break_ == static_cast<unsigned>(v)))
      Access(misc_inherited_data_, access_.misc_inherited_data_)->word_break_ = static_cast<unsigned>(v);
  }
  void ResetWordBreak() {
    Access(misc_inherited_data_, access_.misc_inherited_data_)->word_break_ = static_cast<unsigned>(EWordBreak::kNormal);
  }

  // writing-mode
  WritingMode GetWritingMode() const {
    return static_cast<WritingMode>(data_.writing_mode_);
  }
  void SetWritingMode(WritingMode v) {
    data_.writing_mode_ = static_cast<unsigned>(v);
  }
  void ResetWritingMode() {
    data_.writing_mode_ = static_cast<unsigned>(WritingMode::kHorizontalTb);
  }

protected:
  ComputedStyleBuilderBase() = delete;
  explicit ComputedStyleBuilderBase(const ComputedStyleBase&);
  ComputedStyleBuilderBase(const ComputedStyleBase& source_for_noninherited,
                           const ComputedStyleBase& parent_style);
  // Two builders must not own the same writable group.
  ComputedStyleBuilderBase(const ComputedStyleBuilderBase&) = delete;
  ComputedStyleBuilderBase(ComputedStyleBuilderBase&&) = default;
  ComputedStyleBuilderBase& operator=(const ComputedStyleBuilderBase&) = delete;
  ComputedStyleBuilderBase& operator=(ComputedStyleBuilderBase&&) = default;

  // EffectiveZoom
  void SetEffectiveZoomInternal(float v) {
    if (!(misc_inherited_data_->misc_inherited_2_data_->effective_zoom_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->effective_zoom_ = v;
  }

  // font
  const Font& FontInternal() const {
    return inherited_data_->font_;
  }
  Font& MutableFontInternal() {
    return Access(inherited_data_, access_.inherited_data_)->font_;
  }

  // hyphenate-limit-chars
  StyleHyphenateLimitChars& MutableHyphenateLimitCharsInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenate_limit_chars_;
  }

  // hyphenate-character
  AtomicString& MutableHyphenationStringInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->hyphenation_string_;
  }

  // -internal-legacy-paint
  PlatformPaint& MutableLegacyPaintInternal() {
    return Access(inherited_data_, access_.inherited_data_)->legacy_paint_;
  }

  // line-height
  const Length& LineHeightInternal() const {
    return inherited_data_->line_height_;
  }
  Length& MutableLineHeightInternal() {
    return Access(inherited_data_, access_.inherited_data_)->line_height_;
  }

  // tab-size
  void SetTabSizeInternal(const TabSize& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->tab_size_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->tab_size_ = v;
  }
  void SetTabSizeInternal(TabSize&& v) {
    if (!(misc_inherited_data_->misc_inherited_1_data_->tab_size_ == v))
      Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->tab_size_ = std::move(v);
  }
  TabSize& MutableTabSizeInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->tab_size_;
  }

  // text-decoration-color
  const StyleColorValue& TextDecorationColor() const {
    return misc_data_->misc_5_data_->text_decoration_color_;
  }
  StyleColorValue& MutableTextDecorationColorInternal() {
    return Access(Access(misc_data_, access_.misc_data_)->misc_5_data_, access_.misc_5_data_)->text_decoration_color_;
  }

  // text-decoration-thickness
  TextDecorationThickness& MutableTextDecorationThicknessInternal() {
    return Access(Access(misc_data_, access_.misc_data_)->misc_6_data_, access_.misc_6_data_)->text_decoration_thickness_;
  }

  // text-emphasis-color
  const StyleColorValue& TextEmphasisColor() const {
    return misc_inherited_data_->misc_inherited_1_data_->text_emphasis_color_;
  }
  StyleColorValue& MutableTextEmphasisColorInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_emphasis_color_;
  }

  // TextEmphasisCustomMark
  AtomicString& MutableTextEmphasisCustomMarkInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_emphasis_custom_mark_;
  }

  // TextEmphasisMark
  TextEmphasisMark TextEmphasisMarkInternal() const {
    return static_cast<TextEmphasisMark>(misc_inherited_data_->text_emphasis_mark_);
  }

  // -webkit-text-fill-color
  const StyleColorValue& TextFillColor() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_fill_color_;
  }
  StyleColorValue& MutableTextFillColorInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_fill_color_;
  }

  // text-indent
  Length& MutableTextIndentInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_1_data_, access_.misc_inherited_1_data_)->text_indent_;
  }

  // -webkit-text-stroke-color
  const StyleColorValue& TextStrokeColor() const {
    return misc_inherited_data_->misc_inherited_2_data_->text_stroke_color_;
  }
  StyleColorValue& MutableTextStrokeColorInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_stroke_color_;
  }

  // text-underline-offset
  Length& MutableTextUnderlineOffsetInternal() {
    return Access(Access(misc_inherited_data_, access_.misc_inherited_data_)->misc_inherited_2_data_, access_.misc_inherited_2_data_)->text_underline_offset_;
  }

  // VerticalAlign
  unsigned VerticalAlignInternal() const {
    return static_cast<unsigned>(data_.vertical_align_);
  }
  void SetVerticalAlignInternal(unsigned v) {
    data_.vertical_align_ = static_cast<unsigned>(v);
  }

  // VerticalAlignLength
  void SetVerticalAlignLengthInternal(const Length& v) {
    if (!(box_data_->vertical_align_length_ == v))
      Access(box_data_, access_.box_data_)->vertical_align_length_ = v;
  }
  void SetVerticalAlignLengthInternal(Length&& v) {
    if (!(box_data_->vertical_align_length_ == v))
      Access(box_data_, access_.box_data_)->vertical_align_length_ = std::move(v);
  }
  Length& MutableVerticalAlignLengthInternal() {
    return Access(box_data_, access_.box_data_)->vertical_align_length_;
  }

  void ResetAccess() const {
    access_ = {};
  }

private:
  friend class ComputedStyleBase;

  // Set once this builder holds a private copy of the group. The copy
  // was made by this builder and is not yet shared with any style.
  mutable struct {
    bool box_data_ = false;
    bool inherited_data_ = false;
    bool misc_data_ = false;
    bool misc_inherited_data_ = false;
    bool misc_inherited_1_data_ = false;
    bool misc_inherited_2_data_ = false;
    bool misc_5_data_ = false;
    bool misc_6_data_ = false;
    bool visual_data_ = false;
  } access_;

  template <typename T>
  static T* Access(std::shared_ptr<const T>& data, bool& access_flag) {
    if (!access_flag) {
      data = std::make_shared<T>(*data);
      access_flag = true;
    }
    // The object was created non-const by the copy above.
    return const_cast<T*>(data.get());
  }

  using StyleInheritedData = ComputedStyleBase::StyleInheritedData;
  using StyleMiscInheritedData = ComputedStyleBase::StyleMiscInheritedData;
  using StyleBoxData = ComputedStyleBase::StyleBoxData;
  using StyleVisualData = ComputedStyleBase::StyleVisualData;
  using StyleMiscData = ComputedStyleBase::StyleMiscData;

  std::shared_ptr<const StyleInheritedData> inherited_data_;
  std::shared_ptr<const StyleMiscInheritedData> misc_inherited_data_;
  std::shared_ptr<const StyleBoxData> box_data_;
  std::shared_ptr<const StyleVisualData> visual_data_;
  std::shared_ptr<const StyleMiscData> misc_data_;
  ComputedStyleBase::Data data_;
};

} // namespace bkfont
