// Generated by tools/style/make_css_properties.py from
// blink/renderer/core/css/css_properties.json5. Do not edit.
// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license in LICENSE.
#pragma once

#include <cstdint>
#include <span>
#include <string_view>

namespace bkit {

// Only ported properties have IDs. Longhands come first (high-priority
// longhands before the others), then shorthands, then aliases, each in
// upstream order.
enum class CSSPropertyID : uint16_t {
  kInvalid = 0,
  kColor,
  kDirection,
  kFontFamily,
  kFontFeatureSettings,
  kFontKerning,
  kFontOpticalSizing,
  kFontPalette,
  kFontSize,
  kFontSizeAdjust,
  kFontStretch,
  kFontStyle,
  kFontSynthesisSmallCaps,
  kFontSynthesisStyle,
  kFontSynthesisWeight,
  kFontVariantAlternates,
  kFontVariantCaps,
  kFontVariantEastAsian,
  kFontVariantEmoji,
  kFontVariantLigatures,
  kFontVariantNumeric,
  kFontVariantPosition,
  kFontVariationSettings,
  kFontWeight,
  kTextOrientation,
  kTextRendering,
  kTextSpacingTrim,
  kWebkitFontSmoothing,
  kWebkitLocale,
  kWebkitTextOrientation,
  kWebkitWritingMode,
  kWritingMode,
  kHyphenateCharacter,
  kHyphenateLimitChars,
  kHyphens,
  kLetterSpacing,
  kLineBreak,
  kLineHeight,
  kOverflowWrap,
  kTabSize,
  kTextAlign,
  kTextAlignLast,
  kTextAutospace,
  kTextCombineUpright,
  kTextDecorationColor,
  kTextDecorationLine,
  kTextDecorationSkipInk,
  kTextDecorationStyle,
  kTextDecorationThickness,
  kTextEmphasisColor,
  kTextEmphasisPosition,
  kTextEmphasisStyle,
  kTextIndent,
  kTextShadow,
  kTextTransform,
  kTextUnderlineOffset,
  kTextUnderlinePosition,
  kTextWrapMode,
  kTextWrapStyle,
  kUnicodeBidi,
  kVerticalAlign,
  kVisibility,
  kWebkitLineBreak,
  kWebkitTextFillColor,
  kWebkitTextStrokeColor,
  kWebkitTextStrokeWidth,
  kWhiteSpaceCollapse,
  kWordBreak,
  kWordSpacing,
  kFont,
  kFontSynthesis,
  kFontVariant,
  kTextDecoration,
  kTextEmphasis,
  kTextWrap,
  kWebkitTextStroke,
  kWhiteSpace,
  kAliasEpubTextEmphasis,
  kAliasEpubTextEmphasisColor,
  kAliasEpubTextEmphasisStyle,
  kAliasEpubTextOrientation,
  kAliasEpubTextTransform,
  kAliasEpubWordBreak,
  kAliasEpubWritingMode,
  kAliasWebkitFontFeatureSettings,
  kAliasWebkitHyphenateCharacter,
  kAliasWebkitTextEmphasis,
  kAliasWebkitTextEmphasisColor,
  kAliasWebkitTextEmphasisPosition,
  kAliasWebkitTextEmphasisStyle,
  kAliasWordWrap,
  kCount
};

inline constexpr CSSPropertyID kFirstCSSProperty = CSSPropertyID::kColor;
inline constexpr CSSPropertyID kLastHighPriorityCSSProperty = CSSPropertyID::kWritingMode;
inline constexpr CSSPropertyID kLastLonghandCSSProperty = CSSPropertyID::kWordSpacing;
inline constexpr CSSPropertyID kFirstShorthandCSSProperty = CSSPropertyID::kFont;
inline constexpr CSSPropertyID kLastCSSProperty = CSSPropertyID::kWhiteSpace;
inline constexpr CSSPropertyID kFirstCSSPropertyAlias = CSSPropertyID::kAliasEpubTextEmphasis;
inline constexpr int kNumCSSPropertyIDs = static_cast<int>(CSSPropertyID::kCount);
inline constexpr int kNumCSSLonghands = 68;

constexpr bool IsHighPriority(CSSPropertyID id) {
  return id >= kFirstCSSProperty && id <= kLastHighPriorityCSSProperty;
}
constexpr bool IsLonghand(CSSPropertyID id) {
  return id >= kFirstCSSProperty && id <= kLastLonghandCSSProperty;
}
constexpr bool IsShorthand(CSSPropertyID id) {
  return id >= kFirstShorthandCSSProperty && id <= kLastCSSProperty;
}
constexpr bool IsPropertyAlias(CSSPropertyID id) {
  return id >= kFirstCSSPropertyAlias && id < CSSPropertyID::kCount;
}

struct CSSPropertyMetadata {
  CSSPropertyID id;
  std::string_view name;
  bool inherited;
  // css_properties.json5 "surrogate_for": a legacy longhand which is
  // cascaded as the named property. kInvalid when none.
  CSSPropertyID surrogate_for;
  // css_properties.json5 "logical_property_group": the group name
  // (empty when in none) and whether this member is the logical one.
  std::string_view logical_property_group;
  bool is_logical;
  // The resolved property of an alias; kInvalid otherwise.
  CSSPropertyID alias_for;
  // The longhands a shorthand expands to, in StylePropertyShorthand
  // order. Empty for longhands and aliases.
  std::span<const CSSPropertyID> longhands;
};

std::span<const CSSPropertyMetadata> CSSProperties();
const CSSPropertyMetadata* GetCSSPropertyMetadata(CSSPropertyID);
// The property an alias stands for; other IDs are returned unchanged.
CSSPropertyID ResolveCSSPropertyID(CSSPropertyID);
// The ID of a property or alias by CSS name; kInvalid if not ported.
CSSPropertyID CSSPropertyIDFromName(std::string_view);
// CSSProperty::IsInSameLogicalPropertyGroupWithDifferentMappingLogic().
bool IsInSameLogicalPropertyGroupWithDifferentMappingLogic(CSSPropertyID, CSSPropertyID);

} // namespace bkit
