// Generated by tools/style/make_css_properties.py from
// blink/renderer/core/css/css_properties.json5. Do not edit.
// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license in LICENSE.
#include "css_property_names.h"

#include <array>

namespace bkit {
namespace {

constexpr CSSPropertyID kFontLonghands[] = {
    CSSPropertyID::kFontStyle,
    CSSPropertyID::kFontVariantLigatures,
    CSSPropertyID::kFontVariantCaps,
    CSSPropertyID::kFontVariantNumeric,
    CSSPropertyID::kFontVariantEastAsian,
    CSSPropertyID::kFontVariantAlternates,
    CSSPropertyID::kFontVariantPosition,
    CSSPropertyID::kFontVariantEmoji,
    CSSPropertyID::kFontWeight,
    CSSPropertyID::kFontStretch,
    CSSPropertyID::kFontSize,
    CSSPropertyID::kLineHeight,
    CSSPropertyID::kFontFamily,
    CSSPropertyID::kFontOpticalSizing,
    CSSPropertyID::kFontSizeAdjust,
    CSSPropertyID::kFontKerning,
    CSSPropertyID::kFontFeatureSettings,
    CSSPropertyID::kFontVariationSettings,
};
constexpr CSSPropertyID kFontSynthesisLonghands[] = {
    CSSPropertyID::kFontSynthesisWeight,
    CSSPropertyID::kFontSynthesisStyle,
    CSSPropertyID::kFontSynthesisSmallCaps,
};
constexpr CSSPropertyID kFontVariantLonghands[] = {
    CSSPropertyID::kFontVariantLigatures,
    CSSPropertyID::kFontVariantCaps,
    CSSPropertyID::kFontVariantAlternates,
    CSSPropertyID::kFontVariantNumeric,
    CSSPropertyID::kFontVariantEastAsian,
    CSSPropertyID::kFontVariantPosition,
    CSSPropertyID::kFontVariantEmoji,
};
constexpr CSSPropertyID kTextDecorationLonghands[] = {
    CSSPropertyID::kTextDecorationLine,
    CSSPropertyID::kTextDecorationThickness,
    CSSPropertyID::kTextDecorationStyle,
    CSSPropertyID::kTextDecorationColor,
};
constexpr CSSPropertyID kTextEmphasisLonghands[] = {
    CSSPropertyID::kTextEmphasisStyle,
    CSSPropertyID::kTextEmphasisColor,
};
constexpr CSSPropertyID kTextWrapLonghands[] = {
    CSSPropertyID::kTextWrapMode,
    CSSPropertyID::kTextWrapStyle,
};
constexpr CSSPropertyID kWebkitTextStrokeLonghands[] = {
    CSSPropertyID::kWebkitTextStrokeWidth,
    CSSPropertyID::kWebkitTextStrokeColor,
};
constexpr CSSPropertyID kWhiteSpaceLonghands[] = {
    CSSPropertyID::kWhiteSpaceCollapse,
    CSSPropertyID::kTextWrapMode,
};

constexpr CSSPropertyMetadata kProperties[] = {
    {CSSPropertyID::kColor, "color", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kDirection, "direction", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontFamily, "font-family", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontFeatureSettings, "font-feature-settings", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontKerning, "font-kerning", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontOpticalSizing, "font-optical-sizing", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontPalette, "font-palette", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontSize, "font-size", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontSizeAdjust, "font-size-adjust", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontStretch, "font-stretch", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontStyle, "font-style", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontSynthesisSmallCaps, "font-synthesis-small-caps", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontSynthesisStyle, "font-synthesis-style", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontSynthesisWeight, "font-synthesis-weight", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariantAlternates, "font-variant-alternates", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariantCaps, "font-variant-caps", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariantEastAsian, "font-variant-east-asian", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariantEmoji, "font-variant-emoji", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariantLigatures, "font-variant-ligatures", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariantNumeric, "font-variant-numeric", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariantPosition, "font-variant-position", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontVariationSettings, "font-variation-settings", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFontWeight, "font-weight", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextOrientation, "text-orientation", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextRendering, "text-rendering", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextSpacingTrim, "text-spacing-trim", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitFontSmoothing, "-webkit-font-smoothing", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitLocale, "-webkit-locale", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitTextOrientation, "-webkit-text-orientation", true, CSSPropertyID::kTextOrientation, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitWritingMode, "-webkit-writing-mode", true, CSSPropertyID::kWritingMode, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWritingMode, "writing-mode", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kHyphenateCharacter, "hyphenate-character", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kHyphenateLimitChars, "hyphenate-limit-chars", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kHyphens, "hyphens", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kLetterSpacing, "letter-spacing", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kLineBreak, "line-break", true, CSSPropertyID::kWebkitLineBreak, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kLineHeight, "line-height", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kOverflowWrap, "overflow-wrap", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTabSize, "tab-size", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextAlign, "text-align", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextAlignLast, "text-align-last", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextAutospace, "text-autospace", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextCombineUpright, "text-combine-upright", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextDecorationColor, "text-decoration-color", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextDecorationLine, "text-decoration-line", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextDecorationSkipInk, "text-decoration-skip-ink", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextDecorationStyle, "text-decoration-style", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextDecorationThickness, "text-decoration-thickness", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextEmphasisColor, "text-emphasis-color", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextEmphasisPosition, "text-emphasis-position", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextEmphasisStyle, "text-emphasis-style", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextIndent, "text-indent", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextShadow, "text-shadow", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextTransform, "text-transform", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextUnderlineOffset, "text-underline-offset", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextUnderlinePosition, "text-underline-position", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextWrapMode, "text-wrap-mode", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kTextWrapStyle, "text-wrap-style", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kUnicodeBidi, "unicode-bidi", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kVerticalAlign, "vertical-align", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kVisibility, "visibility", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitLineBreak, "-webkit-line-break", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitTextFillColor, "-webkit-text-fill-color", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitTextStrokeColor, "-webkit-text-stroke-color", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWebkitTextStrokeWidth, "-webkit-text-stroke-width", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWhiteSpaceCollapse, "white-space-collapse", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWordBreak, "word-break", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kWordSpacing, "word-spacing", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, {}},
    {CSSPropertyID::kFont, "font", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kFontLonghands},
    {CSSPropertyID::kFontSynthesis, "font-synthesis", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kFontSynthesisLonghands},
    {CSSPropertyID::kFontVariant, "font-variant", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kFontVariantLonghands},
    {CSSPropertyID::kTextDecoration, "text-decoration", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kTextDecorationLonghands},
    {CSSPropertyID::kTextEmphasis, "text-emphasis", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kTextEmphasisLonghands},
    {CSSPropertyID::kTextWrap, "text-wrap", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kTextWrapLonghands},
    {CSSPropertyID::kWebkitTextStroke, "-webkit-text-stroke", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kWebkitTextStrokeLonghands},
    {CSSPropertyID::kWhiteSpace, "white-space", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kInvalid, kWhiteSpaceLonghands},
    {CSSPropertyID::kAliasEpubTextEmphasis, "-epub-text-emphasis", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextEmphasis, {}},
    {CSSPropertyID::kAliasEpubTextEmphasisColor, "-epub-text-emphasis-color", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextEmphasisColor, {}},
    {CSSPropertyID::kAliasEpubTextEmphasisStyle, "-epub-text-emphasis-style", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextEmphasisStyle, {}},
    {CSSPropertyID::kAliasEpubTextOrientation, "-epub-text-orientation", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kWebkitTextOrientation, {}},
    {CSSPropertyID::kAliasEpubTextTransform, "-epub-text-transform", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextTransform, {}},
    {CSSPropertyID::kAliasEpubWordBreak, "-epub-word-break", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kWordBreak, {}},
    {CSSPropertyID::kAliasEpubWritingMode, "-epub-writing-mode", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kWebkitWritingMode, {}},
    {CSSPropertyID::kAliasWebkitFontFeatureSettings, "-webkit-font-feature-settings", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kFontFeatureSettings, {}},
    {CSSPropertyID::kAliasWebkitHyphenateCharacter, "-webkit-hyphenate-character", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kHyphenateCharacter, {}},
    {CSSPropertyID::kAliasWebkitTextEmphasis, "-webkit-text-emphasis", false, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextEmphasis, {}},
    {CSSPropertyID::kAliasWebkitTextEmphasisColor, "-webkit-text-emphasis-color", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextEmphasisColor, {}},
    {CSSPropertyID::kAliasWebkitTextEmphasisPosition, "-webkit-text-emphasis-position", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextEmphasisPosition, {}},
    {CSSPropertyID::kAliasWebkitTextEmphasisStyle, "-webkit-text-emphasis-style", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kTextEmphasisStyle, {}},
    {CSSPropertyID::kAliasWordWrap, "word-wrap", true, CSSPropertyID::kInvalid, "", false, CSSPropertyID::kOverflowWrap, {}},
};
static_assert(std::size(kProperties) + 1 == static_cast<size_t>(CSSPropertyID::kCount));

constexpr bool MetadataInIDOrder() {
  for (size_t i = 0; i < std::size(kProperties); ++i)
    if (static_cast<size_t>(kProperties[i].id) != i + 1) return false;
  return true;
}
static_assert(MetadataInIDOrder());

} // namespace

std::span<const CSSPropertyMetadata> CSSProperties() {
  return kProperties;
}

const CSSPropertyMetadata* GetCSSPropertyMetadata(CSSPropertyID id) {
  const auto index = static_cast<size_t>(id);
  return index > 0 && index < static_cast<size_t>(CSSPropertyID::kCount) ? &kProperties[index - 1] : nullptr;
}

CSSPropertyID ResolveCSSPropertyID(CSSPropertyID id) {
  if (!IsPropertyAlias(id)) return id;
  return GetCSSPropertyMetadata(id)->alias_for;
}

CSSPropertyID CSSPropertyIDFromName(std::string_view name) {
  for (const auto& property : kProperties)
    if (property.name == name) return property.id;
  return CSSPropertyID::kInvalid;
}

bool IsInSameLogicalPropertyGroupWithDifferentMappingLogic(CSSPropertyID id, CSSPropertyID other) {
  const auto* a = GetCSSPropertyMetadata(id);
  const auto* b = GetCSSPropertyMetadata(other);
  return a && b && !a->logical_property_group.empty() && a->logical_property_group == b->logical_property_group &&
         a->is_logical != b->is_logical;
}

} // namespace bkit
