// Generated by tools/style/make_computed_style_base.py from
// blink/renderer/core/css/css_properties.json5. Do not edit.
// Copyright 2016 The Chromium Authors
// Use of this source code is governed by a BSD-style license in LICENSE.
#pragma once

#include "base/notreached.h"
#include "style/computed_style_base.h"
#include "style/css_value_keywords.h"

namespace bkfont {
namespace detail {

template <class T>
T cssValueIDToPlatformEnumGenerated(CSSValueID);

template <>
inline EOverflowWrap cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNormal: return EOverflowWrap::kNormal;
    case CSSValueID::kBreakWord: return EOverflowWrap::kBreakWord;
    case CSSValueID::kAnywhere: return EOverflowWrap::kAnywhere;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(EOverflowWrap v) {
  switch (v) {
    case EOverflowWrap::kNormal: return CSSValueID::kNormal;
    case EOverflowWrap::kBreakWord: return CSSValueID::kBreakWord;
    case EOverflowWrap::kAnywhere: return CSSValueID::kAnywhere;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextAlign cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kLeft: return ETextAlign::kLeft;
    case CSSValueID::kRight: return ETextAlign::kRight;
    case CSSValueID::kCenter: return ETextAlign::kCenter;
    case CSSValueID::kJustify: return ETextAlign::kJustify;
    case CSSValueID::kWebkitLeft: return ETextAlign::kWebkitLeft;
    case CSSValueID::kWebkitRight: return ETextAlign::kWebkitRight;
    case CSSValueID::kWebkitCenter: return ETextAlign::kWebkitCenter;
    case CSSValueID::kStart: return ETextAlign::kStart;
    case CSSValueID::kEnd: return ETextAlign::kEnd;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextAlign v) {
  switch (v) {
    case ETextAlign::kLeft: return CSSValueID::kLeft;
    case ETextAlign::kRight: return CSSValueID::kRight;
    case ETextAlign::kCenter: return CSSValueID::kCenter;
    case ETextAlign::kJustify: return CSSValueID::kJustify;
    case ETextAlign::kWebkitLeft: return CSSValueID::kWebkitLeft;
    case ETextAlign::kWebkitRight: return CSSValueID::kWebkitRight;
    case ETextAlign::kWebkitCenter: return CSSValueID::kWebkitCenter;
    case ETextAlign::kStart: return CSSValueID::kStart;
    case ETextAlign::kEnd: return CSSValueID::kEnd;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextAlignLast cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kLeft: return ETextAlignLast::kLeft;
    case CSSValueID::kRight: return ETextAlignLast::kRight;
    case CSSValueID::kCenter: return ETextAlignLast::kCenter;
    case CSSValueID::kJustify: return ETextAlignLast::kJustify;
    case CSSValueID::kAuto: return ETextAlignLast::kAuto;
    case CSSValueID::kStart: return ETextAlignLast::kStart;
    case CSSValueID::kEnd: return ETextAlignLast::kEnd;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextAlignLast v) {
  switch (v) {
    case ETextAlignLast::kLeft: return CSSValueID::kLeft;
    case ETextAlignLast::kRight: return CSSValueID::kRight;
    case ETextAlignLast::kCenter: return CSSValueID::kCenter;
    case ETextAlignLast::kJustify: return CSSValueID::kJustify;
    case ETextAlignLast::kAuto: return CSSValueID::kAuto;
    case ETextAlignLast::kStart: return CSSValueID::kStart;
    case ETextAlignLast::kEnd: return CSSValueID::kEnd;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextAutospace cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNormal: return ETextAutospace::kNormal;
    case CSSValueID::kNoAutospace: return ETextAutospace::kNoAutospace;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextAutospace v) {
  switch (v) {
    case ETextAutospace::kNormal: return CSSValueID::kNormal;
    case ETextAutospace::kNoAutospace: return CSSValueID::kNoAutospace;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextCombine cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNone: return ETextCombine::kNone;
    case CSSValueID::kAll: return ETextCombine::kAll;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextCombine v) {
  switch (v) {
    case ETextCombine::kNone: return CSSValueID::kNone;
    case ETextCombine::kAll: return CSSValueID::kAll;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextDecorationSkipInk cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNone: return ETextDecorationSkipInk::kNone;
    case CSSValueID::kAuto: return ETextDecorationSkipInk::kAuto;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextDecorationSkipInk v) {
  switch (v) {
    case ETextDecorationSkipInk::kNone: return CSSValueID::kNone;
    case ETextDecorationSkipInk::kAuto: return CSSValueID::kAuto;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextDecorationStyle cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kDotted: return ETextDecorationStyle::kDotted;
    case CSSValueID::kDashed: return ETextDecorationStyle::kDashed;
    case CSSValueID::kSolid: return ETextDecorationStyle::kSolid;
    case CSSValueID::kDouble: return ETextDecorationStyle::kDouble;
    case CSSValueID::kWavy: return ETextDecorationStyle::kWavy;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextDecorationStyle v) {
  switch (v) {
    case ETextDecorationStyle::kDotted: return CSSValueID::kDotted;
    case ETextDecorationStyle::kDashed: return CSSValueID::kDashed;
    case ETextDecorationStyle::kSolid: return CSSValueID::kSolid;
    case ETextDecorationStyle::kDouble: return CSSValueID::kDouble;
    case ETextDecorationStyle::kWavy: return CSSValueID::kWavy;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextOrientation cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kMixed: return ETextOrientation::kMixed;
    case CSSValueID::kSideways: return ETextOrientation::kSideways;
    case CSSValueID::kUpright: return ETextOrientation::kUpright;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextOrientation v) {
  switch (v) {
    case ETextOrientation::kMixed: return CSSValueID::kMixed;
    case ETextOrientation::kSideways: return CSSValueID::kSideways;
    case ETextOrientation::kUpright: return CSSValueID::kUpright;
    default: break;
  }
  NOTREACHED();
}

template <>
inline ETextTransform cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNone: return ETextTransform::kNone;
    case CSSValueID::kCapitalize: return ETextTransform::kCapitalize;
    case CSSValueID::kUppercase: return ETextTransform::kUppercase;
    case CSSValueID::kLowercase: return ETextTransform::kLowercase;
    case CSSValueID::kMathAuto: return ETextTransform::kMathAuto;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(ETextTransform v) {
  switch (v) {
    case ETextTransform::kNone: return CSSValueID::kNone;
    case ETextTransform::kCapitalize: return CSSValueID::kCapitalize;
    case ETextTransform::kUppercase: return CSSValueID::kUppercase;
    case ETextTransform::kLowercase: return CSSValueID::kLowercase;
    case ETextTransform::kMathAuto: return CSSValueID::kMathAuto;
    default: break;
  }
  NOTREACHED();
}

template <>
inline EVisibility cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kHidden: return EVisibility::kHidden;
    case CSSValueID::kVisible: return EVisibility::kVisible;
    case CSSValueID::kCollapse: return EVisibility::kCollapse;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(EVisibility v) {
  switch (v) {
    case EVisibility::kHidden: return CSSValueID::kHidden;
    case EVisibility::kVisible: return CSSValueID::kVisible;
    case EVisibility::kCollapse: return CSSValueID::kCollapse;
    default: break;
  }
  NOTREACHED();
}

template <>
inline EWordBreak cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNormal: return EWordBreak::kNormal;
    case CSSValueID::kBreakAll: return EWordBreak::kBreakAll;
    case CSSValueID::kKeepAll: return EWordBreak::kKeepAll;
    case CSSValueID::kAutoPhrase: return EWordBreak::kAutoPhrase;
    case CSSValueID::kBreakWord: return EWordBreak::kBreakWord;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(EWordBreak v) {
  switch (v) {
    case EWordBreak::kNormal: return CSSValueID::kNormal;
    case EWordBreak::kBreakAll: return CSSValueID::kBreakAll;
    case EWordBreak::kKeepAll: return CSSValueID::kKeepAll;
    case EWordBreak::kAutoPhrase: return CSSValueID::kAutoPhrase;
    case EWordBreak::kBreakWord: return CSSValueID::kBreakWord;
    default: break;
  }
  NOTREACHED();
}

template <>
inline Hyphens cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNone: return Hyphens::kNone;
    case CSSValueID::kAuto: return Hyphens::kAuto;
    case CSSValueID::kManual: return Hyphens::kManual;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(Hyphens v) {
  switch (v) {
    case Hyphens::kNone: return CSSValueID::kNone;
    case Hyphens::kAuto: return CSSValueID::kAuto;
    case Hyphens::kManual: return CSSValueID::kManual;
    default: break;
  }
  NOTREACHED();
}

template <>
inline LineBreak cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNormal: return LineBreak::kNormal;
    case CSSValueID::kAuto: return LineBreak::kAuto;
    case CSSValueID::kLoose: return LineBreak::kLoose;
    case CSSValueID::kStrict: return LineBreak::kStrict;
    case CSSValueID::kAfterWhiteSpace: return LineBreak::kAfterWhiteSpace;
    case CSSValueID::kAnywhere: return LineBreak::kAnywhere;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(LineBreak v) {
  switch (v) {
    case LineBreak::kNormal: return CSSValueID::kNormal;
    case LineBreak::kAuto: return CSSValueID::kAuto;
    case LineBreak::kLoose: return CSSValueID::kLoose;
    case LineBreak::kStrict: return CSSValueID::kStrict;
    case LineBreak::kAfterWhiteSpace: return CSSValueID::kAfterWhiteSpace;
    case LineBreak::kAnywhere: return CSSValueID::kAnywhere;
    default: break;
  }
  NOTREACHED();
}

template <>
inline TextDecorationLine cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNone: return TextDecorationLine::kNone;
    case CSSValueID::kUnderline: return TextDecorationLine::kUnderline;
    case CSSValueID::kOverline: return TextDecorationLine::kOverline;
    case CSSValueID::kLineThrough: return TextDecorationLine::kLineThrough;
    case CSSValueID::kBlink: return TextDecorationLine::kBlink;
    case CSSValueID::kSpellingError: return TextDecorationLine::kSpellingError;
    case CSSValueID::kGrammarError: return TextDecorationLine::kGrammarError;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(TextDecorationLine v) {
  switch (v) {
    case TextDecorationLine::kNone: return CSSValueID::kNone;
    case TextDecorationLine::kUnderline: return CSSValueID::kUnderline;
    case TextDecorationLine::kOverline: return CSSValueID::kOverline;
    case TextDecorationLine::kLineThrough: return CSSValueID::kLineThrough;
    case TextDecorationLine::kBlink: return CSSValueID::kBlink;
    case TextDecorationLine::kSpellingError: return CSSValueID::kSpellingError;
    case TextDecorationLine::kGrammarError: return CSSValueID::kGrammarError;
    default: break;
  }
  NOTREACHED();
}

template <>
inline TextDirection cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kLtr: return TextDirection::kLtr;
    case CSSValueID::kRtl: return TextDirection::kRtl;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(TextDirection v) {
  switch (v) {
    case TextDirection::kLtr: return CSSValueID::kLtr;
    case TextDirection::kRtl: return CSSValueID::kRtl;
    default: break;
  }
  NOTREACHED();
}

template <>
inline TextEmphasisFill cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kFilled: return TextEmphasisFill::kFilled;
    case CSSValueID::kOpen: return TextEmphasisFill::kOpen;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(TextEmphasisFill v) {
  switch (v) {
    case TextEmphasisFill::kFilled: return CSSValueID::kFilled;
    case TextEmphasisFill::kOpen: return CSSValueID::kOpen;
    default: break;
  }
  NOTREACHED();
}

template <>
inline TextEmphasisMark cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNone: return TextEmphasisMark::kNone;
    case CSSValueID::kAuto: return TextEmphasisMark::kAuto;
    case CSSValueID::kDot: return TextEmphasisMark::kDot;
    case CSSValueID::kCircle: return TextEmphasisMark::kCircle;
    case CSSValueID::kDoubleCircle: return TextEmphasisMark::kDoubleCircle;
    case CSSValueID::kTriangle: return TextEmphasisMark::kTriangle;
    case CSSValueID::kSesame: return TextEmphasisMark::kSesame;
    case CSSValueID::kCustom: return TextEmphasisMark::kCustom;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(TextEmphasisMark v) {
  switch (v) {
    case TextEmphasisMark::kNone: return CSSValueID::kNone;
    case TextEmphasisMark::kAuto: return CSSValueID::kAuto;
    case TextEmphasisMark::kDot: return CSSValueID::kDot;
    case TextEmphasisMark::kCircle: return CSSValueID::kCircle;
    case TextEmphasisMark::kDoubleCircle: return CSSValueID::kDoubleCircle;
    case TextEmphasisMark::kTriangle: return CSSValueID::kTriangle;
    case TextEmphasisMark::kSesame: return CSSValueID::kSesame;
    case TextEmphasisMark::kCustom: return CSSValueID::kCustom;
    default: break;
  }
  NOTREACHED();
}

template <>
inline TextUnderlinePosition cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kAuto: return TextUnderlinePosition::kAuto;
    case CSSValueID::kFromFont: return TextUnderlinePosition::kFromFont;
    case CSSValueID::kUnder: return TextUnderlinePosition::kUnder;
    case CSSValueID::kLeft: return TextUnderlinePosition::kLeft;
    case CSSValueID::kRight: return TextUnderlinePosition::kRight;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(TextUnderlinePosition v) {
  switch (v) {
    case TextUnderlinePosition::kAuto: return CSSValueID::kAuto;
    case TextUnderlinePosition::kFromFont: return CSSValueID::kFromFont;
    case TextUnderlinePosition::kUnder: return CSSValueID::kUnder;
    case TextUnderlinePosition::kLeft: return CSSValueID::kLeft;
    case TextUnderlinePosition::kRight: return CSSValueID::kRight;
    default: break;
  }
  NOTREACHED();
}

template <>
inline TextWrapMode cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNowrap: return TextWrapMode::kNowrap;
    case CSSValueID::kWrap: return TextWrapMode::kWrap;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(TextWrapMode v) {
  switch (v) {
    case TextWrapMode::kNowrap: return CSSValueID::kNowrap;
    case TextWrapMode::kWrap: return CSSValueID::kWrap;
    default: break;
  }
  NOTREACHED();
}

template <>
inline TextWrapStyle cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kAuto: return TextWrapStyle::kAuto;
    case CSSValueID::kPretty: return TextWrapStyle::kPretty;
    case CSSValueID::kBalance: return TextWrapStyle::kBalance;
    case CSSValueID::kStable: return TextWrapStyle::kStable;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(TextWrapStyle v) {
  switch (v) {
    case TextWrapStyle::kAuto: return CSSValueID::kAuto;
    case TextWrapStyle::kPretty: return CSSValueID::kPretty;
    case TextWrapStyle::kBalance: return CSSValueID::kBalance;
    case TextWrapStyle::kStable: return CSSValueID::kStable;
    default: break;
  }
  NOTREACHED();
}

template <>
inline UnicodeBidi cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kNormal: return UnicodeBidi::kNormal;
    case CSSValueID::kEmbed: return UnicodeBidi::kEmbed;
    case CSSValueID::kBidiOverride: return UnicodeBidi::kBidiOverride;
    case CSSValueID::kIsolate: return UnicodeBidi::kIsolate;
    case CSSValueID::kPlaintext: return UnicodeBidi::kPlaintext;
    case CSSValueID::kIsolateOverride: return UnicodeBidi::kIsolateOverride;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(UnicodeBidi v) {
  switch (v) {
    case UnicodeBidi::kNormal: return CSSValueID::kNormal;
    case UnicodeBidi::kEmbed: return CSSValueID::kEmbed;
    case UnicodeBidi::kBidiOverride: return CSSValueID::kBidiOverride;
    case UnicodeBidi::kIsolate: return CSSValueID::kIsolate;
    case UnicodeBidi::kPlaintext: return CSSValueID::kPlaintext;
    case UnicodeBidi::kIsolateOverride: return CSSValueID::kIsolateOverride;
    default: break;
  }
  NOTREACHED();
}

template <>
inline WhiteSpaceCollapse cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kCollapse: return WhiteSpaceCollapse::kCollapse;
    case CSSValueID::kPreserve: return WhiteSpaceCollapse::kPreserve;
    case CSSValueID::kPreserveBreaks: return WhiteSpaceCollapse::kPreserveBreaks;
    case CSSValueID::kBreakSpaces: return WhiteSpaceCollapse::kBreakSpaces;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(WhiteSpaceCollapse v) {
  switch (v) {
    case WhiteSpaceCollapse::kCollapse: return CSSValueID::kCollapse;
    case WhiteSpaceCollapse::kPreserve: return CSSValueID::kPreserve;
    case WhiteSpaceCollapse::kPreserveBreaks: return CSSValueID::kPreserveBreaks;
    case WhiteSpaceCollapse::kBreakSpaces: return CSSValueID::kBreakSpaces;
    default: break;
  }
  NOTREACHED();
}

template <>
inline WritingMode cssValueIDToPlatformEnumGenerated(CSSValueID v) {
  switch (v) {
    case CSSValueID::kHorizontalTb: return WritingMode::kHorizontalTb;
    case CSSValueID::kVerticalRl: return WritingMode::kVerticalRl;
    case CSSValueID::kVerticalLr: return WritingMode::kVerticalLr;
    case CSSValueID::kSidewaysRl: return WritingMode::kSidewaysRl;
    case CSSValueID::kSidewaysLr: return WritingMode::kSidewaysLr;
    default: break;
  }
  NOTREACHED();
}

inline CSSValueID platformEnumToCSSValueIDGenerated(WritingMode v) {
  switch (v) {
    case WritingMode::kHorizontalTb: return CSSValueID::kHorizontalTb;
    case WritingMode::kVerticalRl: return CSSValueID::kVerticalRl;
    case WritingMode::kVerticalLr: return CSSValueID::kVerticalLr;
    case WritingMode::kSidewaysRl: return CSSValueID::kSidewaysRl;
    case WritingMode::kSidewaysLr: return CSSValueID::kSidewaysLr;
    default: break;
  }
  NOTREACHED();
}

} // namespace detail
} // namespace bkfont
